-- BTC testnet P2WSH multisig wallet initialization.
-- This script intentionally removes legacy multi-coin tables and historical test data.

BEGIN;

DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
  LOOP
    EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
  END LOOP;
END $$;

CREATE TABLE best_block_height (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency      INT NOT NULL UNIQUE,
  height        BIGINT NOT NULL DEFAULT 0,
  interval_time BIGINT NOT NULL DEFAULT 300000,
  create_date   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE currency_balance (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency_index INT NOT NULL UNIQUE,
  balance        DECIMAL(32,8) NOT NULL DEFAULT 0,
  create_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE btc_address (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  address         VARCHAR(128) NOT NULL,
  network         VARCHAR(32) NOT NULL DEFAULT 'testnet3',
  script_type     VARCHAR(32) NOT NULL DEFAULT 'P2WSH',
  redeem_script   TEXT NOT NULL DEFAULT '',
  witness_script  TEXT NOT NULL DEFAULT '',
  derivation_path VARCHAR(128) NOT NULL DEFAULT '',
  public_keys     TEXT NOT NULL DEFAULT '',
  balance         DECIMAL(32,8) NOT NULL DEFAULT 0,
  biz             INT NOT NULL,
  nonce           INT NOT NULL DEFAULT 0,
  index           INT NOT NULL,
  status          SMALLINT NOT NULL DEFAULT 0,
  create_date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (address),
  UNIQUE (user_id, biz, index)
);

CREATE TABLE btc_utxo_transaction (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_id        VARCHAR(128) NOT NULL,
  block_height BIGINT NOT NULL DEFAULT 0,
  address      VARCHAR(128) NOT NULL,
  balance      DECIMAL(32,8) NOT NULL,
  confirm_num  BIGINT NOT NULL DEFAULT 0,
  biz          INT NOT NULL,
  seq          SMALLINT NOT NULL,
  spent        SMALLINT NOT NULL DEFAULT 0,
  status       SMALLINT NOT NULL DEFAULT 0,
  credited     BOOLEAN NOT NULL DEFAULT FALSE,
  spent_tx_id  VARCHAR(128) NOT NULL DEFAULT 'unspent',
  create_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tx_id, seq)
);

CREATE INDEX idx_btc_utxo_available
  ON btc_utxo_transaction (status, confirm_num, spent_tx_id);
CREATE INDEX idx_btc_utxo_address
  ON btc_utxo_transaction (address);

CREATE TABLE ltc_address (
  LIKE btc_address INCLUDING DEFAULTS INCLUDING IDENTITY
);

ALTER TABLE ltc_address
  ADD PRIMARY KEY (id),
  ADD UNIQUE (address),
  ADD UNIQUE (user_id, biz, index);

CREATE TABLE ltc_utxo_transaction (
  LIKE btc_utxo_transaction INCLUDING DEFAULTS INCLUDING IDENTITY
);

ALTER TABLE ltc_utxo_transaction
  ADD PRIMARY KEY (id),
  ADD UNIQUE (tx_id, seq);

CREATE INDEX idx_ltc_utxo_available
  ON ltc_utxo_transaction (status, confirm_num, spent_tx_id);
CREATE INDEX idx_ltc_utxo_address
  ON ltc_utxo_transaction (address);

CREATE TABLE btc_withdraw_record (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_id       VARCHAR(128) NOT NULL DEFAULT 'waiting',
  address     VARCHAR(128) NOT NULL,
  user_id     BIGINT NOT NULL,
  balance     DECIMAL(32,8) NOT NULL,
  fee         DECIMAL(32,8) NOT NULL DEFAULT 0,
  currency    INT NOT NULL,
  biz         INT NOT NULL,
  withdraw_id VARCHAR(128) NOT NULL,
  status      SMALLINT NOT NULL DEFAULT 0,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (withdraw_id)
);

CREATE INDEX idx_btc_withdraw_record_tx_id
  ON btc_withdraw_record (tx_id);
CREATE INDEX idx_btc_withdraw_record_status
  ON btc_withdraw_record (status);

CREATE TABLE ltc_withdraw_record (
  LIKE btc_withdraw_record INCLUDING DEFAULTS INCLUDING IDENTITY
);

ALTER TABLE ltc_withdraw_record
  ADD PRIMARY KEY (id),
  ADD UNIQUE (withdraw_id);

CREATE INDEX idx_ltc_withdraw_record_tx_id
  ON ltc_withdraw_record (tx_id);
CREATE INDEX idx_ltc_withdraw_record_status
  ON ltc_withdraw_record (status);

CREATE TABLE btc_withdraw_transaction (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_id       VARCHAR(128) NOT NULL DEFAULT '',
  balance     DECIMAL(32,8) NOT NULL,
  signature   TEXT,
  currency    INT NOT NULL,
  status      SMALLINT NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_btc_withdraw_transaction_tx_id
  ON btc_withdraw_transaction (tx_id);
CREATE INDEX idx_btc_withdraw_transaction_status
  ON btc_withdraw_transaction (status);

CREATE TABLE ltc_withdraw_transaction (
  LIKE btc_withdraw_transaction INCLUDING DEFAULTS INCLUDING IDENTITY
);

ALTER TABLE ltc_withdraw_transaction
  ADD PRIMARY KEY (id);

CREATE INDEX idx_ltc_withdraw_transaction_tx_id
  ON ltc_withdraw_transaction (tx_id);
CREATE INDEX idx_ltc_withdraw_transaction_status
  ON ltc_withdraw_transaction (status);

CREATE TABLE user_asset (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  currency    INT NOT NULL,
  balance     DECIMAL(32,8) NOT NULL DEFAULT 0,
  frozen      DECIMAL(32,8) NOT NULL DEFAULT 0,
  version     INT NOT NULL DEFAULT 0,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, currency)
);

CREATE TABLE system_param (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  param_key   VARCHAR(128) NOT NULL UNIQUE,
  param_value TEXT NOT NULL,
  remark      VARCHAR(255) NOT NULL DEFAULT '',
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wallet_multisig_config (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency            INT NOT NULL,
  network             VARCHAR(32) NOT NULL,
  script_type         VARCHAR(32) NOT NULL,
  required_signatures INT NOT NULL,
  total_pubkeys       INT NOT NULL,
  pub_key_1           TEXT NOT NULL,
  pub_key_2           TEXT NOT NULL,
  pub_key_3           TEXT NOT NULL,
  derivation_template VARCHAR(128) NOT NULL,
  create_date         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (currency, network, script_type)
);

INSERT INTO best_block_height (id, currency, height, interval_time)
VALUES (1, 1, 0, 300000);

INSERT INTO best_block_height (currency, height, interval_time)
VALUES (24, 0, 300000);

INSERT INTO currency_balance (id, currency_index, balance)
VALUES (1, 1, 0);

INSERT INTO currency_balance (currency_index, balance)
VALUES (24, 0);

INSERT INTO wallet_multisig_config (
  id, currency, network, script_type, required_signatures, total_pubkeys,
  pub_key_1, pub_key_2, pub_key_3, derivation_template
) VALUES (
  1,
  1,
  'testnet3',
  'P2WSH',
  2,
  3,
  'tpubD6NzVbkrYhZ4YeTnP6ae6en8YvKSvxvvCwh5X7gNpwqEeix6o7etGgsyGywcB9gS1bGTmC4WfLKAdK6vxDEzedd7PMRLcYk5yZLj5JkLAVB',
  'tpubD6NzVbkrYhZ4WuN2bmdffo5p894oRYGQVCfKe3TKT4QVw7qQT18jG1FYbYyB3ePESejLdfaEFMRpsYGVjb4Bh6HiiWaSU8iJRVE46EirNBT',
  'tpubD6NzVbkrYhZ4XKeuSHwv2p3snJxWjacFsu2rEEht2qMaM5FYV2RkbMaJEYNZGK7B3i8D46RTs83DJNPh2Jd5MzXivXCiHLbqAFKv8MKxrC4',
  'm/44/{currency}/{biz}/{userId}/{index}'
);

INSERT INTO wallet_multisig_config (
  currency, network, script_type, required_signatures, total_pubkeys,
  pub_key_1, pub_key_2, pub_key_3, derivation_template
) VALUES (
  24,
  'litecoin-testnet',
  'P2WSH',
  2,
  3,
  'tpubD6NzVbkrYhZ4YeTnP6ae6en8YvKSvxvvCwh5X7gNpwqEeix6o7etGgsyGywcB9gS1bGTmC4WfLKAdK6vxDEzedd7PMRLcYk5yZLj5JkLAVB',
  'tpubD6NzVbkrYhZ4WuN2bmdffo5p894oRYGQVCfKe3TKT4QVw7qQT18jG1FYbYyB3ePESejLdfaEFMRpsYGVjb4Bh6HiiWaSU8iJRVE46EirNBT',
  'tpubD6NzVbkrYhZ4XKeuSHwv2p3snJxWjacFsu2rEEht2qMaM5FYV2RkbMaJEYNZGK7B3i8D46RTs83DJNPh2Jd5MzXivXCiHLbqAFKv8MKxrC4',
  'm/44/{coinType}/{biz}/{userId}/{index}'
);

INSERT INTO btc_address (
  id, user_id, address, network, script_type, redeem_script, witness_script,
  derivation_path, public_keys, balance, biz, nonce, index, status
) VALUES (
  1,
  0,
  'tb1qq293kx3yfs8nlf0uhcr95djscj5rgj6l7ym94r5ke7w5dzhtypuqpprlev',
  'testnet3',
  'P2WSH',
  '',
  '5221029087e7293ac187c98703f91f424b5a90c8b7a1d4306a6b5a0fad5e5268d5c5252103c9262396e302a9f628ab1f37aef83e3a180374048e8c7abe2d70c9a02e3dd5062103fd70f6fa39d8bb618d962b8a29e0b976b546acb3f7e3d7b04d7d7fcad420cc3453ae',
  'm/44/1/0/0/0',
  '029087e7293ac187c98703f91f424b5a90c8b7a1d4306a6b5a0fad5e5268d5c525,03c9262396e302a9f628ab1f37aef83e3a180374048e8c7abe2d70c9a02e3dd506,03fd70f6fa39d8bb618d962b8a29e0b976b546acb3f7e3d7b04d7d7fcad420cc34',
  0,
  0,
  0,
  0,
  0
);

INSERT INTO system_param (param_key, param_value, remark) VALUES
  ('wallet.network', 'testnet3', 'BTC testnet only'),
  ('wallet.script_type', 'P2WSH', 'Native SegWit 2-of-3 multisig'),
  ('wallet.deposit_confirmations', '1', 'Minimum confirmations before crediting user asset'),
  ('wallet.withdraw_confirmations', '6', 'Target confirmations for withdrawal state tracking'),
  ('wallet.fee_rate_sat_vb', '10', 'Default fee rate in sat/vB'),
  ('wallet.scan_start_height', '0', 'Initial scan height');

SELECT setval(pg_get_serial_sequence('best_block_height', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('currency_balance', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('btc_address', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('wallet_multisig_config', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('system_param', 'id'), 6, true);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wallet') THEN
    ALTER TABLE best_block_height OWNER TO wallet;
    ALTER TABLE currency_balance OWNER TO wallet;
    ALTER TABLE btc_address OWNER TO wallet;
    ALTER TABLE btc_utxo_transaction OWNER TO wallet;
    ALTER TABLE btc_withdraw_record OWNER TO wallet;
    ALTER TABLE btc_withdraw_transaction OWNER TO wallet;
    ALTER TABLE ltc_address OWNER TO wallet;
    ALTER TABLE ltc_utxo_transaction OWNER TO wallet;
    ALTER TABLE ltc_withdraw_record OWNER TO wallet;
    ALTER TABLE ltc_withdraw_transaction OWNER TO wallet;
    ALTER TABLE user_asset OWNER TO wallet;
    ALTER TABLE system_param OWNER TO wallet;
    ALTER TABLE wallet_multisig_config OWNER TO wallet;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO wallet;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO wallet;
  END IF;
END $$;

COMMIT;
