#server config
server.port=8002
server.error.whitelabel.enabled=false
logging.file.path=./logs
spring.application.name=wallet-server
#data source
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/wallet
spring.datasource.username=wallet
spring.datasource.password=wallet123
spring.datasource.hikari.maximum-pool-size=20
#feign
feign.client.config.default.connectTimeout=10000
feign.client.config.default.readTimeout=40000
feign.hystrix.enabled=false
#proxy
atomex.innerProxy=http://innerproxy.atomex.pro
#alarm
atomex.warning.contacts=13261645368
#pubKey
atomex.wallet.pubKey1=tpubD6NzVbkrYhZ4X4tuLUxPpCvAZBWXW2mju3nt7RzmczFVYuLqieUacCQ2snjhu8zE9EagGrkG5gxthYUFhpgYx4bEVM9dYraywwZHycJNg5d
atomex.wallet.pubKey2=tpubD6NzVbkrYhZ4WpEJatAtP8DJjva1o2cbV8LbnhLNLrMCaUmF3rUMRFgsVneh53JipwKMwUp3QGGzqff7avf5M9QLR7RZaEy3ha5ihtrkDRQ
atomex.wallet.pubKey3=tpubD6NzVbkrYhZ4XDJNtex5Gm1Hzj4bbewgop6stxxZv4trZ3YFdLk1p9VvzQtYTk8Lf4BMo5pWA5TwJGgFbbEFaBr5Ft951V2wYQcMLWQNji4
atomex.wallet.network=test
#job scheduler center
#task.center.serverList=task.center.serverList
#task.center.namespace=task.center.namespace
#开发环境设置
atomex.app.env.name=dev
#btc config (publicnode testnet - # strips method name from URL path)
atomex.btc.server=https://bitcoin-rpc.publicnode.com#
atomex.btc.server.user=
atomex.btc.server.pwd=
#ltc config
atomex.ltc.server=http://127.0.0.1:18332
atomex.ltc.server.user=test
atomex.ltc.server.pwd=123456
#bch config
atomex.bch.server=http://127.0.0.1:18332
atomex.bch.server.user=test
atomex.bch.server.pwd=123456
#bch config
#usdt config
atomex.usdt.server=http://127.0.0.1:18332
atomex.usdt.server.user=test
atomex.usdt.server.pwd=123456
atomex.usdt.withdraw.address=123456
#eth config
#atomex.eth.server=http://pub-node1.etherscan.io:8545
atomex.eth.server=http://10.40.16.182:7001
atomex.eth.server.user=user
atomex.eth.server.pwd=password
atomex.eth.withdraw.address=0x8dc1b89df4bda67d241c3d88afb6b95038c1cdcc
#etc config
atomex.etc.server=http://54.65.183.172:10005
atomex.etc.server.user=user
atomex.etc.server.pwd=password
atomex.etc.withdraw.address=0x8dc1b89df4bda67d241c3d88afb6b95038c1cdcc
#act config
atomex.act.server=http://192.168.24.28:7001/rpc
atomex.act.server.user=admin
atomex.act.server.pwd=123456
atomex.act.withdraw.address=ACT6wXG7mUmV8rY6DZbQZQCdeeAsWXAWixo1
atomex.act.wallet.name=wallet
atomex.act.wallet.password=atomex0987act
atomex.act.account.name=atomex0987act
#ssc
atomex.ssc.server=http://192.168.24.28:7002/rpc
atomex.ssc.server.user=admin
atomex.ssc.server.pwd=123456
atomex.ssc.withdraw.address=SSCFGm1SoWPsQ3BRs1N9raMWsaDcKaxpz8ET
atomex.ssc.wallet.name=wallet
atomex.ssc.wallet.password=atomex0987ssc
atomex.ssc.account.name=atomex0987ssc
#xrp config
atomex.xrp.server=http://s1.ripple.com:51234
atomex.xrp.withdraw.address=rpi6YSvG1V9npkGGwXjdiBuVrC4d4ZTXdF
#iota
atomex.iota.server=node.iotawallet.info:14265
#of config
atomex.of.server=http://192.168.102.42:7002
atomex.of.withdraw.address=0x000018009cd72f992b5b74f34679bddde7826b5ccf6ba8c552
#ont config
atomex.ont.server=http://192.168.102.75:7001
atomex.ont.withdraw.address=ANrB7NVGYS56pRxWfPt2v1BfQQki3ka3QZ
atomex.ont.pubKey=xpub661MyMwAqRbcFBCPpX2NWrk3FnwzDRfQdm1wxYwDSuzngdKNaN5Ac7eC8Y1LPhWbeRtLridKdPeNpCGmoqQzzobPrLQ3FfLKoyaM1MkBWtK
atomex.ong.claim.to.address=AUSmEuaqm4TqVhBnvUMK6bWvsbWcjU7tgK
#neo
atomex.neo.server=http://192.168.102.42:7001
atomex.neo.withdraw.address=AGihh7mcFWEZdNqopRowsZwCBoN87hf4Ki
#neo use secp256r1
atomex.neo.pubKey=xpub661MyMwAqRbcFBCPpX2NWrk3FnwzDRfQdm1wxYwDSuzngdKNaN5Ac7eC8Y1LPhWbeRtLridKdPeNpCGmoqQzzobPrLQ3FfLKoyaM1MkBWtK
#btm
atomex.btm.server=http://localhost:9888
atomex.btm.pubKey=49CbsCEDtemY4mcMMPEbpkLgg7hRyJhCNY1qpkZWJb8kQ3wjQEkwXN728S3sC2NTUTM5UUsc9NNd58t3urQJLtmz
#eos
atomex.eos.server=https://eos.greymass.com
atomex.eos.withdraw.address=coinmexisgod
#xlm config
atomex.xlm.server=https://horizon.stellar.org
atomex.xlm.withdraw.address=GDVIO2JXJGJWL3K2EJGAOWA4N3K7LI423S7R66NJYIQGQHW72IVDFD5F
#eosc
atomex.eosc.server=https://w1.eosforce.cn
atomex.eosc.withdraw.address=hexing
#tron
atomex.tron.server=grpc.trongrid.io:50051
atomex.tron.pubkey=xpub661MyMwAqRbcFBCPpX2NWrk3FnwzDRfQdm1wxYwDSuzngdKNaN5Ac7eC8WQVuSWiuqKoVQT2Qk6r5E9KDCPUFZyXXcFS4y4977zLmssnL6J
atomex.tron.withdraw.address=TQNkWNfn53g4YxSJHQs1fxbPoorw8hV9Vz
#dogecoin config
atomex.doge.server=http://192.168.102.42:7500
atomex.doge.server.user=dogecoinrpc
atomex.doge.server.pwd=BxZQdQW8wHHjRrQ5YxVSesATLSEvdSQ3Du2Ww13XqTum
atomex.doge.pubkey=xpub661MyMwAqRbcFBCPpX2NWrk3FnwzDRfQdm1wxYwDSuzngdKNaN5Ac7eC8WQVuSWiuqKoVQT2Qk6r5E9KDCPUFZyXXcFS4y4977zLmssnL6J
#xem
atomex.xem.server=http://192.168.102.113:7001
atomex.xem.withdraw.address=NCWWAXRGCEIXWMALJTEHP47YPQCYC32GGWXSO3MZ
#dash config
atomex.dash.server=http://192.168.102.42:7500
atomex.dash.server.user=dashcoin
atomex.dash.server.pwd=123456
atomex.dash.pubkey=xpub661MyMwAqRbcFBCPpX2NWrk3FnwzDRfQdm1wxYwDSuzngdKNaN5Ac7eC8WQVuSWiuqKoVQT2Qk6r5E9KDCPUFZyXXcFS4y4977zLmssnL6J
#luckywin config
atomex.luckywin.server=http://mainnet.luckywin.io
atomex.luckywin.withdraw.address=0xb678872dbcb100d3450c622e1d3fefa226251043
atomex.luckywin.pubkey=xpub661MyMwAqRbcFBCPpX2NWrk3FnwzDRfQdm1wxYwDSuzngdKNaN5Ac7eC8WQVuSWiuqKoVQT2Qk6r5E9KDCPUFZyXXcFS4y4977zLmssnL6J
#zcash config
atomex.zcash.server=http://192.168.102.113:8232
atomex.zcash.server.user=username
atomex.zcash.server.pwd=password
#RBTC config
atomex.rbtc.server=http://192.168.102.109:7510
atomex.rbtc.withdraw.address=0x051567f56c6914896ee959114fe0f4c0958cbc56
atomex.rbtc.pubkey=xpub661MyMwAqRbcFBCPpX2NWrk3FnwzDRfQdm1wxYwDSuzngdKNaN5Ac7eC8WQVuSWiuqKoVQT2Qk6r5E9KDCPUFZyXXcFS4y4977zLmssnL6J
# Nacos service discovery
spring.cloud.nacos.discovery.server-addr=nacos.atomex.pro:8848
spring.cloud.nacos.discovery.namespace=c9d64380-5fa8-428d-9b81-73b3f69272bc