spring.profiles.active=dev
spring.cloud.nacos.discovery.server-addr=nacos.atomex.pro:8848
spring.cloud.nacos.discovery.namespace=c9d64380-5fa8-428d-9b81-73b3f69272bc
spring.cloud.nacos.config.server-addr=${spring.cloud.nacos.discovery.server-addr}
spring.cloud.nacos.config.namespace=${spring.cloud.nacos.discovery.namespace}
spring.cloud.nacos.config.file-extension=yaml
