#logging config
server.port=8004
logging.config=classpath:logback-spring.xml
logging.level.default=INFO
logging.path=logs/
spring.application.name=wallet-sig1
#redis
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
atomex.wallet.network=test
#key
atomex.wallet.masterKey=tprv8ZgxMBicQKsPdbs7SqHoQoG3z9zbLhaqKkC6puxUCiT6iR656FezRhnAhdykJjLanDqqZRGimT8yvHM7sZmWAXeEvk8UPxVMSZ1sh6uJFJc
atomex.wallet.pubKey1=tpubD6NzVbkrYhZ4X4tuLUxPpCvAZBWXW2mju3nt7RzmczFVYuLqieUacCQ2snjhu8zE9EagGrkG5gxthYUFhpgYx4bEVM9dYraywwZHycJNg5d
atomex.wallet.pubKey2=tpubD6NzVbkrYhZ4WpEJatAtP8DJjva1o2cbV8LbnhLNLrMCaUmF3rUMRFgsVneh53JipwKMwUp3QGGzqff7avf5M9QLR7RZaEy3ha5ihtrkDRQ
atomex.wallet.pubKey3=tpubD6NzVbkrYhZ4XDJNtex5Gm1Hzj4bbewgop6stxxZv4trZ3YFdLk1p9VvzQtYTk8Lf4BMo5pWA5TwJGgFbbEFaBr5Ft951V2wYQcMLWQNji4

