-- Synchronize the EVM chain configurations added on 2026-07-26.
-- The baseline init file is tracked by a fixed filename on deployed databases, so its
-- later seed additions are not replayed automatically. This migration contains only
-- the missing chain configuration data and is safe to retry through its UPSERT keys.
--
-- Scope: BERACHAIN, GNOSIS, CELO, MONAD, WORLD_CHAIN, INK, TAIKO, SONEIUM, MODE, LISK, KATANA, MEGAETH, X_LAYER, DEGEN, ROBINHOOD_CHAIN, ETHERLINK, IOTA_EVM, OASIS_EMERALD, CRONOS, SONIC, PULSECHAIN, ZETACHAIN, CORE, SOMNIA, RONIN, CHILIZ, IOTEX, KAIA, PLASMA, STORY, SEI, CONFLUX, VECTOR_SMART_CHAIN, KROWN
--
-- Manual rollback (only if none of these chains has acquired business data):
-- delete matching chain_rpc_node rows, token_config rows, chain_profile rows, then
-- chain_asset rows in that order. Keep rollback manual so deployment never removes
-- wallet configuration automatically.

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('surprising-wallet:20260726:new-evm-chain-config'));

INSERT INTO "public"."chain_asset" ("chain", "symbol", "asset_kind", "contract_address", "decimals",
                                    "native_asset", "active", "min_transfer", "min_withdraw",
                                    "created_at", "updated_at")
VALUES
    ('BERACHAIN', 'BERA', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('BERACHAIN', 'USDC', 'ERC20', '0x549943e04f40284185054145c6E4e9568C1D3241', 6, false, true, 1, 1, now(), now()),
    ('BERACHAIN', 'USDT0', 'ERC20', '0x779Ded0c9e1022225f8E0630b35a9b54bE713736', 6, false, true, 1, 1, now(), now()),
    ('GNOSIS', 'XDAI', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('GNOSIS', 'USDC', 'ERC20', '0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83', 6, false, true, 1, 1, now(), now()),
    ('GNOSIS', 'USDT', 'ERC20', '0x4ECaBa5870353805a9F068101A40E0f32ed605C6', 6, false, true, 1, 1, now(), now()),
    ('CELO', 'CELO', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('CELO', 'USDC', 'ERC20', '0xcebA9300f2b948710d2653dD7B07f33A8B32118C', 6, false, true, 1, 1, now(), now()),
    ('CELO', 'USDT', 'ERC20', '0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e', 6, false, true, 1, 1, now(), now()),
    ('MONAD', 'MON', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('MONAD', 'USDC', 'ERC20', '0x754704Bc059F8C67012fEd69BC8A327a5aafb603', 6, false, true, 1, 1, now(), now()),
    ('MONAD', 'USDT0', 'ERC20', '0xe7cd86e13AC4309349F30B3435a9d337750fC82D', 6, false, true, 1, 1, now(), now()),
    ('WORLD_CHAIN', 'ETH_WORLD', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('WORLD_CHAIN', 'USDC', 'ERC20', '0x79A02482A880bCE3F13e09Da970dC34db4CD24d1', 6, false, true, 1, 1, now(), now()),
    ('INK', 'ETH_INK', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('INK', 'USDC_E', 'ERC20', '0xF1815bd50389c46847f0Bda824eC8da914045D14', 6, false, true, 1, 1, now(), now()),
    ('INK', 'USDT0', 'ERC20', '0x0200C29006150606B650577BBE7B6248F58470c1', 6, false, true, 1, 1, now(), now()),
    ('TAIKO', 'ETH_TAIKO', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('SONEIUM', 'ETH_SONEIUM', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('SONEIUM', 'USDC_E', 'ERC20', '0xbA9986D2381edf1DA03B0B9c1f8b00dc4AacC369', 6, false, true, 1, 1, now(), now()),
    ('SONEIUM', 'USDT', 'ERC20', '0x3A337a6adA9d885b6Ad95ec48F9b75f197b5AE35', 6, false, true, 1, 1, now(), now()),
    ('MODE', 'ETH_MODE', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('MODE', 'USDC', 'ERC20', '0xd988097fb8612cc24eeC14542bC03424c656005f', 6, false, true, 1, 1, now(), now()),
    ('MODE', 'USDT', 'ERC20', '0xf0F161fDA2712DB8b566946122a5af183995e2eD', 6, false, true, 1, 1, now(), now()),
    ('LISK', 'ETH_LISK', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('LISK', 'USDC_E', 'ERC20', '0xF242275d3a6527d877f2c927a82D9b057609cc71', 6, false, true, 1, 1, now(), now()),
    ('KATANA', 'ETH_KATANA', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('KATANA', 'USDC', 'ERC20', '0x203A662b0BD271A6ed5a60EdFbd04bFce608FD36', 6, false, true, 1, 1, now(), now()),
    ('KATANA', 'USDT', 'ERC20', '0x2DCa96907fde857dd3D816880A0df407eeB2D2F2', 6, false, true, 1, 1, now(), now()),
    ('MEGAETH', 'ETH_MEGAETH', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('MEGAETH', 'USDM', 'ERC20', '0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7', 18, false, true, 1, 1, now(), now()),
    ('X_LAYER', 'OKB', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('X_LAYER', 'USDC', 'ERC20', '0x74b7F16337b8972027F6196A17a631aC6dE26d22', 6, false, true, 1, 1, now(), now()),
    ('X_LAYER', 'USDT', 'ERC20', '0x1E4a5963aBFD975d8c9021ce480b42188849D41d', 6, false, true, 1, 1, now(), now()),
    ('DEGEN', 'DEGEN', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('DEGEN', 'USDC', 'ERC20', '0xF1815bd50389c46847f0Bda824eC8da914045D14', 6, false, true, 1, 1, now(), now()),
    ('DEGEN', 'USDT', 'ERC20', '0x674843C06FF83502ddb4D37c2E09C01cdA38cbc8', 6, false, true, 1, 1, now(), now()),
    ('ROBINHOOD_CHAIN', 'ETH_ROBINHOOD', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('ROBINHOOD_CHAIN', 'USDG', 'ERC20', '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168', 6, false, true, 1, 1, now(), now()),
    ('ETHERLINK', 'XTZ', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('ETHERLINK', 'USDC', 'ERC20', '0x796Ea11Fa2dD751eD01b53C372fFDB4AAa8f00F9', 6, false, true, 1, 1, now(), now()),
    ('ETHERLINK', 'USDT', 'ERC20', '0x2C03058C8AFC06713be23e58D2febC8337dbfE6A', 6, false, true, 1, 1, now(), now()),
    ('IOTA_EVM', 'IOTA', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('IOTA_EVM', 'USDC_E', 'ERC20', '0xFbDa5F676cB37624f28265A144A48B0d6e87d3b6', 6, false, true, 1, 1, now(), now()),
    ('IOTA_EVM', 'USDT', 'ERC20', '0xC1B8045A6ef2934Cf0f78B0dbD489969Fa9Be7E4', 6, false, true, 1, 1, now(), now()),
    ('OASIS_EMERALD', 'ROSE', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('CRONOS', 'CRO', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('CRONOS', 'USDC', 'ERC20', '0x3D7F2C478aAfdB65542BCB44bCeeC05849999d2D', 6, false, true, 1, 1, now(), now()),
    ('CRONOS', 'USDT', 'ERC20', '0x66e428c3f67a68878562e79A0234c1F83c208770', 6, false, true, 1, 1, now(), now()),
    ('SONIC', 'S', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('SONIC', 'USDC', 'ERC20', '0x29219dd400f2Bf60E5a23d13Be72B486D4038894', 6, false, true, 1, 1, now(), now()),
    ('SONIC', 'USDT', 'ERC20', '0x6047828dc181963ba44974801ff68e538da5eaf9', 6, false, true, 1, 1, now(), now()),
    ('PULSECHAIN', 'PLS', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('PULSECHAIN', 'USDC', 'ERC20', '0x15d38573d2Feeb82e7ad5187aB8c1D52810B1f07', 6, false, true, 1, 1, now(), now()),
    ('PULSECHAIN', 'USDT', 'ERC20', '0x0cb6F5a34ad42ec934882A05265A7d5f59b51A2f', 6, false, true, 1, 1, now(), now()),
    ('ZETACHAIN', 'ZETA', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('ZETACHAIN', 'USDC_ETH', 'ERC20', '0x0cbe0dF132a6c6B4a2974Fa1b7Fb953CF0Cc798a', 6, false, true, 1, 1, now(), now()),
    ('ZETACHAIN', 'USDT_ETH', 'ERC20', '0x7c8dDa80bbBE1254a7aACf3219EBe1481c6E01d7', 6, false, true, 1, 1, now(), now()),
    ('CORE', 'CORE', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('CORE', 'USDC', 'ERC20', '0xa4151b2b3e269645181dccf2d426ce75fcbdeca9', 6, false, true, 1, 1, now(), now()),
    ('CORE', 'USDT', 'ERC20', '0x900101d06a7426441ae63e9ab3b9b0f63be145f1', 6, false, true, 1, 1, now(), now()),
    ('SOMNIA', 'SOMI', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('SOMNIA', 'USDC_E', 'ERC20', '0x28bec7e30e6faee657a03e19bf1128aad7632a00', 6, false, true, 1, 1, now(), now()),
    ('SOMNIA', 'USDT', 'ERC20', '0x67B302E35Aef5EEE8c32D934F5856869EF428330', 6, false, true, 1, 1, now(), now()),
    ('RONIN', 'RON', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('RONIN', 'USDC', 'ERC20', '0x0B7007c13325C48911F73A2daD5FA5dCBf808aDc', 6, false, true, 1, 1, now(), now()),
    ('CHILIZ', 'CHZ', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('CHILIZ', 'USDC', 'ERC20', '0xa37936F56249965d407E39347528a1A91eB1cbef', 6, false, true, 1, 1, now(), now()),
    ('CHILIZ', 'USDT', 'ERC20', '0x37C57a89812a0D492AeEd7691F1610CA0a8f74A1', 6, false, true, 1, 1, now(), now()),
    ('IOTEX', 'IOTX', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('IOTEX', 'USDC_E', 'ERC20', '0xcdf79194c6c285077a58da47641d4dbe51f63542', 6, false, true, 1, 1, now(), now()),
    ('IOTEX', 'IOUSDT', 'ERC20', '0x6fbcdc1169b5130c59e72e51ed68a84841c98cd1', 6, false, true, 1, 1, now(), now()),
    ('KAIA', 'KAIA', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('KAIA', 'USDT', 'ERC20', '0xd077a400968890eacc75cdc901f0356c943e4fdb', 6, false, true, 1, 1, now(), now()),
    ('PLASMA', 'XPL', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('PLASMA', 'USDT0', 'ERC20', '0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb', 6, false, true, 1, 1, now(), now()),
    ('STORY', 'IP', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('STORY', 'USDC_E', 'ERC20', '0xF1815bd50389c46847f0Bda824eC8da914045D14', 6, false, true, 1, 1, now(), now()),
    ('SEI', 'SEI', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('SEI', 'USDC', 'ERC20', '0xe15fC38F6D8c56aF07bbCBe3BAf5708A2Bf42392', 6, false, true, 1, 1, now(), now()),
    ('SEI', 'USDT0', 'ERC20', '0x9151434b16b9763660705744891fA906F660EcC5', 6, false, true, 1, 1, now(), now()),
    ('CONFLUX', 'CFX', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('CONFLUX', 'USDC_E', 'ERC20', '0x6963efed0ab40f6c3d7bda44a05dcf1437c44372', 18, false, true, 1, 1, now(), now()),
    ('CONFLUX', 'USDT0', 'ERC20', '0xaf37e8b6c9ed7f6318979f56fc287d76c30847ff', 6, false, true, 1, 1, now(), now()),
    ('VECTOR_SMART_CHAIN', 'VSG', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('KROWN', 'KROWN', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now())
ON CONFLICT ("chain", "symbol") DO UPDATE SET
    "asset_kind" = EXCLUDED."asset_kind",
    "contract_address" = EXCLUDED."contract_address",
    "decimals" = EXCLUDED."decimals",
    "native_asset" = EXCLUDED."native_asset",
    "active" = EXCLUDED."active",
    "min_transfer" = EXCLUDED."min_transfer",
    "min_withdraw" = EXCLUDED."min_withdraw",
    "updated_at" = now();

INSERT INTO "public"."token_config" ("chain", "symbol", "standard", "contract_address", "decimals", "enabled",
                                     "min_deposit", "min_withdraw", "collect_enabled", "created_at", "updated_at",
                                     "network", "token_standard", "min_deposit_amount", "min_withdraw_amount",
                                     "collect_threshold", "gas_strategy", "confirmation_required")
VALUES
    ('BERACHAIN', 'USDC', 'ERC20', '0x549943e04f40284185054145c6E4e9568C1D3241', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('BERACHAIN', 'USDT0', 'ERC20', '0x779Ded0c9e1022225f8E0630b35a9b54bE713736', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('GNOSIS', 'USDC', 'ERC20', '0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('GNOSIS', 'USDT', 'ERC20', '0x4ECaBa5870353805a9F068101A40E0f32ed605C6', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CELO', 'USDC', 'ERC20', '0xcebA9300f2b948710d2653dD7B07f33A8B32118C', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CELO', 'USDT', 'ERC20', '0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('MONAD', 'USDC', 'ERC20', '0x754704Bc059F8C67012fEd69BC8A327a5aafb603', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('MONAD', 'USDT0', 'ERC20', '0xe7cd86e13AC4309349F30B3435a9d337750fC82D', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('WORLD_CHAIN', 'USDC', 'ERC20', '0x79A02482A880bCE3F13e09Da970dC34db4CD24d1', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('INK', 'USDC_E', 'ERC20', '0xF1815bd50389c46847f0Bda824eC8da914045D14', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('INK', 'USDT0', 'ERC20', '0x0200C29006150606B650577BBE7B6248F58470c1', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SONEIUM', 'USDC_E', 'ERC20', '0xbA9986D2381edf1DA03B0B9c1f8b00dc4AacC369', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SONEIUM', 'USDT', 'ERC20', '0x3A337a6adA9d885b6Ad95ec48F9b75f197b5AE35', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('MODE', 'USDC', 'ERC20', '0xd988097fb8612cc24eeC14542bC03424c656005f', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('MODE', 'USDT', 'ERC20', '0xf0F161fDA2712DB8b566946122a5af183995e2eD', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('LISK', 'USDC_E', 'ERC20', '0xF242275d3a6527d877f2c927a82D9b057609cc71', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('KATANA', 'USDC', 'ERC20', '0x203A662b0BD271A6ed5a60EdFbd04bFce608FD36', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('KATANA', 'USDT', 'ERC20', '0x2DCa96907fde857dd3D816880A0df407eeB2D2F2', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('MEGAETH', 'USDM', 'ERC20', '0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7', 18, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('X_LAYER', 'USDC', 'ERC20', '0x74b7F16337b8972027F6196A17a631aC6dE26d22', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('X_LAYER', 'USDT', 'ERC20', '0x1E4a5963aBFD975d8c9021ce480b42188849D41d', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('DEGEN', 'USDC', 'ERC20', '0xF1815bd50389c46847f0Bda824eC8da914045D14', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('DEGEN', 'USDT', 'ERC20', '0x674843C06FF83502ddb4D37c2E09C01cdA38cbc8', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('ROBINHOOD_CHAIN', 'USDG', 'ERC20', '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('ETHERLINK', 'USDC', 'ERC20', '0x796Ea11Fa2dD751eD01b53C372fFDB4AAa8f00F9', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('ETHERLINK', 'USDT', 'ERC20', '0x2C03058C8AFC06713be23e58D2febC8337dbfE6A', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('IOTA_EVM', 'USDC_E', 'ERC20', '0xFbDa5F676cB37624f28265A144A48B0d6e87d3b6', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('IOTA_EVM', 'USDT', 'ERC20', '0xC1B8045A6ef2934Cf0f78B0dbD489969Fa9Be7E4', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CRONOS', 'USDC', 'ERC20', '0x3D7F2C478aAfdB65542BCB44bCeeC05849999d2D', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CRONOS', 'USDT', 'ERC20', '0x66e428c3f67a68878562e79A0234c1F83c208770', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SONIC', 'USDC', 'ERC20', '0x29219dd400f2Bf60E5a23d13Be72B486D4038894', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SONIC', 'USDT', 'ERC20', '0x6047828dc181963ba44974801ff68e538da5eaf9', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('PULSECHAIN', 'USDC', 'ERC20', '0x15d38573d2Feeb82e7ad5187aB8c1D52810B1f07', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('PULSECHAIN', 'USDT', 'ERC20', '0x0cb6F5a34ad42ec934882A05265A7d5f59b51A2f', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('ZETACHAIN', 'USDC_ETH', 'ERC20', '0x0cbe0dF132a6c6B4a2974Fa1b7Fb953CF0Cc798a', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('ZETACHAIN', 'USDT_ETH', 'ERC20', '0x7c8dDa80bbBE1254a7aACf3219EBe1481c6E01d7', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CORE', 'USDC', 'ERC20', '0xa4151b2b3e269645181dccf2d426ce75fcbdeca9', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CORE', 'USDT', 'ERC20', '0x900101d06a7426441ae63e9ab3b9b0f63be145f1', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SOMNIA', 'USDC_E', 'ERC20', '0x28bec7e30e6faee657a03e19bf1128aad7632a00', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SOMNIA', 'USDT', 'ERC20', '0x67B302E35Aef5EEE8c32D934F5856869EF428330', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('RONIN', 'USDC', 'ERC20', '0x0B7007c13325C48911F73A2daD5FA5dCBf808aDc', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CHILIZ', 'USDC', 'ERC20', '0xa37936F56249965d407E39347528a1A91eB1cbef', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CHILIZ', 'USDT', 'ERC20', '0x37C57a89812a0D492AeEd7691F1610CA0a8f74A1', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('IOTEX', 'USDC_E', 'ERC20', '0xcdf79194c6c285077a58da47641d4dbe51f63542', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('IOTEX', 'IOUSDT', 'ERC20', '0x6fbcdc1169b5130c59e72e51ed68a84841c98cd1', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('KAIA', 'USDT', 'ERC20', '0xd077a400968890eacc75cdc901f0356c943e4fdb', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('PLASMA', 'USDT0', 'ERC20', '0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('STORY', 'USDC_E', 'ERC20', '0xF1815bd50389c46847f0Bda824eC8da914045D14', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SEI', 'USDC', 'ERC20', '0xe15fC38F6D8c56aF07bbCBe3BAf5708A2Bf42392', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('SEI', 'USDT0', 'ERC20', '0x9151434b16b9763660705744891fA906F660EcC5', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CONFLUX', 'USDC_E', 'ERC20', '0x6963efed0ab40f6c3d7bda44a05dcf1437c44372', 18, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('CONFLUX', 'USDT0', 'ERC20', '0xaf37e8b6c9ed7f6318979f56fc287d76c30847ff', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1)
ON CONFLICT ("chain", "network", "symbol") DO UPDATE SET
    "standard" = EXCLUDED."standard",
    "contract_address" = EXCLUDED."contract_address",
    "decimals" = EXCLUDED."decimals",
    "enabled" = EXCLUDED."enabled",
    "min_deposit" = EXCLUDED."min_deposit",
    "min_withdraw" = EXCLUDED."min_withdraw",
    "collect_enabled" = EXCLUDED."collect_enabled",
    "network" = EXCLUDED."network",
    "token_standard" = EXCLUDED."token_standard",
    "min_deposit_amount" = EXCLUDED."min_deposit_amount",
    "min_withdraw_amount" = EXCLUDED."min_withdraw_amount",
    "collect_threshold" = EXCLUDED."collect_threshold",
    "gas_strategy" = EXCLUDED."gas_strategy",
    "confirmation_required" = EXCLUDED."confirmation_required",
    "updated_at" = now();

-- Mainnet templates stay disabled for both deposits and collection until the
-- corresponding production chain, RPC and funding controls are approved.
UPDATE "public"."token_config"
SET "collect_enabled" = false,
    "updated_at" = now()
WHERE "chain" IN (
    'BERACHAIN', 'GNOSIS', 'CELO', 'MONAD', 'WORLD_CHAIN', 'INK', 'TAIKO',
    'SONEIUM', 'MODE', 'LISK', 'KATANA', 'MEGAETH', 'X_LAYER', 'DEGEN',
    'ROBINHOOD_CHAIN', 'ETHERLINK', 'IOTA_EVM', 'OASIS_EMERALD', 'CRONOS',
    'SONIC', 'PULSECHAIN', 'ZETACHAIN', 'CORE', 'SOMNIA', 'RONIN', 'CHILIZ',
    'IOTEX', 'KAIA', 'PLASMA', 'STORY', 'SEI', 'CONFLUX',
    'VECTOR_SMART_CHAIN', 'KROWN'
)
  AND "network" = 'mainnet'
  AND "symbol" IN ('USDC', 'USDT')
  AND "enabled" = false
  AND "collect_enabled" = true;

INSERT INTO "public"."chain_profile" ("chain", "network", "family", "runtime_currency_id", "bip44_coin_type",
                                      "native_symbol", "rpc_url", "explorer_url", "deposit_confirmations",
                                      "withdraw_confirmations", "default_fee_rate", "dust_threshold", "enabled",
                                      "created_at", "updated_at", "chain_id", "gas_policy", "scan_batch_size",
                                      "scan_enabled", "withdraw_enabled", "collection_enabled", "transfer_enabled",
                                      "scan_start_height", "scan_max_blocks_per_run")
VALUES
    ('BERACHAIN', 'bepolia', 'evm', 9010, 60, 'BERA',
     'https://bepolia.rpc.berachain.com', 'https://testnet.berascan.com/tx/',
     20, 20, 1, 0, false, now(), now(), 80069, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('BERACHAIN', 'mainnet', 'evm', 9010, 60, 'BERA',
     'https://rpc.berachain.com', 'https://berascan.com/tx/',
     20, 20, 1, 0, false, now(), now(), 80094, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('GNOSIS', 'chiado', 'evm', 9011, 60, 'XDAI',
     'https://rpc.chiadochain.net', 'https://gnosis-chiado.blockscout.com/tx/',
     32, 32, 1, 0, false, now(), now(), 10200, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('GNOSIS', 'mainnet', 'evm', 9011, 60, 'XDAI',
     'https://rpc.gnosischain.com', 'https://gnosisscan.io/tx/',
     32, 32, 1, 0, false, now(), now(), 100, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CELO', 'celo-sepolia', 'evm', 9012, 60, 'CELO',
     'https://forno.celo-sepolia.celo-testnet.org', 'https://celo-sepolia.blockscout.com/tx/',
     40, 40, 1, 0, false, now(), now(), 11142220, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CELO', 'mainnet', 'evm', 9012, 60, 'CELO',
     'https://forno.celo.org', 'https://celoscan.io/tx/',
     40, 40, 1, 0, false, now(), now(), 42220, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('MONAD', 'testnet', 'evm', 9013, 60, 'MON',
     'https://testnet-rpc.monad.xyz', 'https://testnet.monadvision.com/tx/',
     20, 20, 1, 0, false, now(), now(), 10143, 'eip1559', 500,
     false, false, false, false, 0, 500),
    ('MONAD', 'mainnet', 'evm', 9013, 60, 'MON',
     'https://rpc.monad.xyz', 'https://monadvision.com/tx/',
     20, 20, 1, 0, false, now(), now(), 143, 'eip1559', 500,
     false, false, false, false, 0, 500),
    ('WORLD_CHAIN', 'sepolia', 'evm', 9014, 60, 'ETH_WORLD',
     'https://worldchain-sepolia.g.alchemy.com/public', 'https://worldchain-sepolia.explorer.alchemy.com/tx/',
     40, 40, 1, 0, false, now(), now(), 4801, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('WORLD_CHAIN', 'mainnet', 'evm', 9014, 60, 'ETH_WORLD',
     'https://worldchain-mainnet.g.alchemy.com/public', 'https://worldscan.org/tx/',
     40, 40, 1, 0, false, now(), now(), 480, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('INK', 'sepolia', 'evm', 9015, 60, 'ETH_INK',
     'https://rpc-gel-sepolia.inkonchain.com', 'https://explorer-sepolia.inkonchain.com/tx/',
     40, 40, 1, 0, false, now(), now(), 763373, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('INK', 'mainnet', 'evm', 9015, 60, 'ETH_INK',
     'https://rpc-gel.inkonchain.com', 'https://explorer.inkonchain.com/tx/',
     40, 40, 1, 0, false, now(), now(), 57073, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('TAIKO', 'hoodi', 'evm', 9016, 60, 'ETH_TAIKO',
     'https://rpc.hoodi.taiko.xyz', 'https://blockscoutapi.hoodi.taiko.xyz/tx/',
     40, 40, 1, 0, false, now(), now(), 167013, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('TAIKO', 'mainnet', 'evm', 9016, 60, 'ETH_TAIKO',
     'https://rpc.mainnet.taiko.xyz', 'https://blockscoutapi.mainnet.taiko.xyz/tx/',
     40, 40, 1, 0, false, now(), now(), 167000, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SONEIUM', 'minato', 'evm', 9017, 60, 'ETH_SONEIUM',
     'https://rpc.minato.soneium.org', 'https://soneium-minato.blockscout.com/tx/',
     40, 40, 1, 0, false, now(), now(), 1946, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SONEIUM', 'mainnet', 'evm', 9017, 60, 'ETH_SONEIUM',
     'https://rpc.soneium.org', 'https://soneium.blockscout.com/tx/',
     40, 40, 1, 0, false, now(), now(), 1868, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('MODE', 'sepolia', 'evm', 9018, 60, 'ETH_MODE',
     'https://sepolia.mode.network', 'https://sepolia.explorer.mode.network/tx/',
     40, 40, 1, 0, false, now(), now(), 919, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('MODE', 'mainnet', 'evm', 9018, 60, 'ETH_MODE',
     'https://mainnet.mode.network', 'https://explorer.mode.network/tx/',
     40, 40, 1, 0, false, now(), now(), 34443, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('LISK', 'sepolia', 'evm', 9019, 60, 'ETH_LISK',
     'https://rpc.sepolia-api.lisk.com', 'https://sepolia-blockscout.lisk.com/tx/',
     40, 40, 1, 0, false, now(), now(), 4202, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('LISK', 'mainnet', 'evm', 9019, 60, 'ETH_LISK',
     'https://rpc.api.lisk.com', 'https://blockscout.lisk.com/tx/',
     40, 40, 1, 0, false, now(), now(), 1135, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('KATANA', 'bokuto', 'evm', 9020, 60, 'ETH_KATANA',
     'https://rpc-bokuto.katanarpc.com', 'https://bokuto.katanascan.com/tx/',
     40, 40, 1, 0, false, now(), now(), 737373, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('KATANA', 'mainnet', 'evm', 9020, 60, 'ETH_KATANA',
     'https://rpc.katana.network', 'https://katanascan.com/tx/',
     40, 40, 1, 0, false, now(), now(), 747474, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('MEGAETH', 'carrot', 'evm', 9021, 60, 'ETH_MEGAETH',
     'https://carrot.megaeth.com/rpc', 'https://megaeth-testnet-v2.blockscout.com/tx/',
     40, 40, 1, 0, false, now(), now(), 6343, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('MEGAETH', 'mainnet', 'evm', 9021, 60, 'ETH_MEGAETH',
     'https://mainnet.megaeth.com/rpc', 'https://megaeth.blockscout.com/tx/',
     40, 40, 1, 0, false, now(), now(), 4326, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('X_LAYER', 'testnet', 'evm', 9022, 60, 'OKB',
     'https://testrpc.xlayer.tech/terigon', 'https://www.okx.com/web3/explorer/xlayer-test/tx/',
     40, 40, 1, 0, false, now(), now(), 1952, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('X_LAYER', 'mainnet', 'evm', 9022, 60, 'OKB',
     'https://rpc.xlayer.tech', 'https://www.okx.com/web3/explorer/xlayer/tx/',
     40, 40, 1, 0, false, now(), now(), 196, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('DEGEN', 'mainnet', 'evm', 9023, 60, 'DEGEN',
     'https://rpc.degen.tips', 'https://explorer.degen.tips/tx/',
     40, 40, 1, 0, false, now(), now(), 666666666, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('ROBINHOOD_CHAIN', 'testnet', 'evm', 9024, 60, 'ETH_ROBINHOOD',
     'https://rpc.testnet.chain.robinhood.com', 'https://explorer.testnet.chain.robinhood.com/tx/',
     40, 40, 1, 0, false, now(), now(), 46630, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('ROBINHOOD_CHAIN', 'mainnet', 'evm', 9024, 60, 'ETH_ROBINHOOD',
     'https://rpc.mainnet.chain.robinhood.com', 'https://robinhoodchain.blockscout.com/tx/',
     40, 40, 1, 0, false, now(), now(), 4663, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('ETHERLINK', 'shadownet', 'evm', 9025, 60, 'XTZ',
     'https://node.shadownet.etherlink.com', 'https://shadownet.explorer.etherlink.com/tx/',
     40, 40, 1, 0, false, now(), now(), 127823, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('ETHERLINK', 'mainnet', 'evm', 9025, 60, 'XTZ',
     'https://node.mainnet.etherlink.com', 'https://explorer.etherlink.com/tx/',
     40, 40, 1, 0, false, now(), now(), 42793, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('IOTA_EVM', 'testnet', 'evm', 9026, 60, 'IOTA',
     'https://json-rpc.evm.testnet.iotaledger.net', 'https://explorer.evm.testnet.iotaledger.net/tx/',
     40, 40, 1, 0, false, now(), now(), 1076, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('IOTA_EVM', 'mainnet', 'evm', 9026, 60, 'IOTA',
     'https://json-rpc.evm.iotaledger.net', 'https://explorer.evm.iota.org/tx/',
     40, 40, 1, 0, false, now(), now(), 8822, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('OASIS_EMERALD', 'testnet', 'evm', 9027, 60, 'ROSE',
     'https://testnet.emerald.oasis.io', 'https://explorer.oasis.io/testnet/emerald/tx/',
     1, 1, 1, 0, false, now(), now(), 42261, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('OASIS_EMERALD', 'mainnet', 'evm', 9027, 60, 'ROSE',
     'https://emerald.oasis.io', 'https://explorer.oasis.io/mainnet/emerald/tx/',
     1, 1, 1, 0, false, now(), now(), 42262, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CRONOS', 'testnet', 'evm', 9028, 60, 'CRO',
     'https://evm-t3.cronos.org', 'https://explorer.cronos.org/testnet/tx/',
     1, 1, 1, 0, false, now(), now(), 338, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CRONOS', 'mainnet', 'evm', 9028, 60, 'CRO',
     'https://evm.cronos.org', 'https://explorer.cronos.org/tx/',
     1, 1, 1, 0, false, now(), now(), 25, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SONIC', 'testnet', 'evm', 9029, 60, 'S',
     'https://rpc.testnet.soniclabs.com', 'https://testnet.sonicscan.org/tx/',
     1, 1, 1, 0, false, now(), now(), 14601, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SONIC', 'mainnet', 'evm', 9029, 60, 'S',
     'https://rpc.soniclabs.com', 'https://sonicscan.org/tx/',
     1, 1, 1, 0, false, now(), now(), 146, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('PULSECHAIN', 'testnet', 'evm', 9030, 60, 'PLS',
     'https://rpc.v4.testnet.pulsechain.com', 'https://scan.v4.testnet.pulsechain.com/#/tx/',
     1, 1, 1, 0, false, now(), now(), 943, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('PULSECHAIN', 'mainnet', 'evm', 9030, 60, 'PLS',
     'https://rpc.pulsechain.com', 'https://api.scan.pulsechain.com/tx/',
     1, 1, 1, 0, false, now(), now(), 369, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('ZETACHAIN', 'testnet', 'evm', 9031, 60, 'ZETA',
     'https://zetachain-athens-evm.blockpi.network/v1/rpc/public', 'https://zetachain-athens-3.blockscout.com/tx/',
     1, 1, 1, 0, false, now(), now(), 7001, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('ZETACHAIN', 'mainnet', 'evm', 9031, 60, 'ZETA',
     'https://zetachain-evm.blockpi.network/v1/rpc/public', 'https://zetascan.com/tx/',
     1, 1, 1, 0, false, now(), now(), 7000, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CORE', 'testnet', 'evm', 9032, 60, 'CORE',
     'https://rpc.test2.btcs.network', 'https://scan.test2.btcs.network/tx/',
     1, 1, 1, 0, false, now(), now(), 1114, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CORE', 'mainnet', 'evm', 9032, 60, 'CORE',
     'https://rpc.coredao.org', 'https://scan.coredao.org/tx/',
     1, 1, 1, 0, false, now(), now(), 1116, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SOMNIA', 'testnet', 'evm', 9033, 60, 'SOMI',
     'https://dream-rpc.somnia.network', 'https://shannon-explorer.somnia.network/tx/',
     1, 1, 1, 0, false, now(), now(), 50312, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SOMNIA', 'mainnet', 'evm', 9033, 60, 'SOMI',
     'https://api.infra.mainnet.somnia.network', 'https://explorer.somnia.network/tx/',
     1, 1, 1, 0, false, now(), now(), 5031, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('RONIN', 'testnet', 'evm', 9034, 60, 'RON',
     'https://saigon-testnet.roninchain.com/rpc', 'https://saigon-app.roninchain.com/tx/',
     1, 1, 1, 0, false, now(), now(), 202601, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('RONIN', 'mainnet', 'evm', 9034, 60, 'RON',
     'https://api.roninchain.com/rpc', 'https://explorer.roninchain.com/tx/',
     1, 1, 1, 0, false, now(), now(), 2020, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CHILIZ', 'testnet', 'evm', 9035, 60, 'CHZ',
     'https://spicy-rpc.chiliz.com/', 'https://testnet.chiliscan.com/tx/',
     1, 1, 1, 0, false, now(), now(), 88882, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CHILIZ', 'mainnet', 'evm', 9035, 60, 'CHZ',
     'https://chiliz-rpc.publicnode.com', 'https://chiliscan.com/tx/',
     1, 1, 1, 0, false, now(), now(), 88888, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('IOTEX', 'testnet', 'evm', 9036, 60, 'IOTX',
     'https://babel-api.testnet.iotex.io', 'https://testnet.iotexscan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 4690, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('IOTEX', 'mainnet', 'evm', 9036, 60, 'IOTX',
     'https://babel-api.mainnet.iotex.io', 'https://iotexscan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 4689, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('KAIA', 'testnet', 'evm', 9037, 60, 'KAIA',
     'https://public-en-kairos.node.kaia.io', 'https://kairos.kaiascan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 1001, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('KAIA', 'mainnet', 'evm', 9037, 60, 'KAIA',
     'https://public-en.node.kaia.io', 'https://kaiascan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 8217, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('PLASMA', 'testnet', 'evm', 9038, 60, 'XPL',
     'https://testnet-rpc.plasma.to', 'https://testnet.plasmascan.to/tx/',
     1, 1, 1, 0, false, now(), now(), 9746, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('PLASMA', 'mainnet', 'evm', 9038, 60, 'XPL',
     'https://rpc.plasma.to', 'https://plasmascan.to/tx/',
     1, 1, 1, 0, false, now(), now(), 9745, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('STORY', 'testnet', 'evm', 9039, 60, 'IP',
     'https://aeneid.storyrpc.io', 'https://aeneid.storyscan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 1315, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('STORY', 'mainnet', 'evm', 9039, 60, 'IP',
     'https://mainnet.storyrpc.io', 'https://www.storyscan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 1514, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SEI', 'testnet', 'evm', 9040, 60, 'SEI',
     'https://evm-rpc-testnet.sei-apis.com', 'https://testnet.seiscan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 1328, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('SEI', 'mainnet', 'evm', 9040, 60, 'SEI',
     'https://evm-rpc.sei-apis.com', 'https://seiscan.io/tx/',
     1, 1, 1, 0, false, now(), now(), 1329, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CONFLUX', 'testnet', 'evm', 9041, 60, 'CFX',
     'https://evmtestnet.confluxrpc.com', 'https://evmtestnet.confluxscan.org/tx/',
     1, 1, 1, 0, false, now(), now(), 71, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('CONFLUX', 'mainnet', 'evm', 9041, 60, 'CFX',
     'https://evm.confluxrpc.com', 'https://evm.confluxscan.org/tx/',
     400, 400, 400, 0, false, now(), now(), 1030, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('VECTOR_SMART_CHAIN', 'mainnet', 'evm', 9042, 60, 'VSG',
     'https://rpc.vscblockchain.org', 'https://explorer.vscblockchain.org/tx/',
     12, 12, 12, 0, false, now(), now(), 420042, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('KROWN', 'mainnet', 'evm', 9043, 60, 'KROWN',
     'https://mainnet.krown.network', 'https://explorer.krown.network/tx/',
     12, 12, 12, 0, false, now(), now(), 1983, 'eip1559', 200,
     false, false, false, false, 0, 200)
ON CONFLICT ("chain", "network") DO UPDATE SET
    "family" = EXCLUDED."family",
    "runtime_currency_id" = EXCLUDED."runtime_currency_id",
    "bip44_coin_type" = EXCLUDED."bip44_coin_type",
    "native_symbol" = EXCLUDED."native_symbol",
    "rpc_url" = EXCLUDED."rpc_url",
    "explorer_url" = EXCLUDED."explorer_url",
    "deposit_confirmations" = EXCLUDED."deposit_confirmations",
    "withdraw_confirmations" = EXCLUDED."withdraw_confirmations",
    "default_fee_rate" = EXCLUDED."default_fee_rate",
    "dust_threshold" = EXCLUDED."dust_threshold",
    "enabled" = EXCLUDED."enabled",
    "updated_at" = now(),
    "chain_id" = EXCLUDED."chain_id",
    "gas_policy" = EXCLUDED."gas_policy",
    "scan_batch_size" = EXCLUDED."scan_batch_size",
    "scan_enabled" = EXCLUDED."scan_enabled",
    "withdraw_enabled" = EXCLUDED."withdraw_enabled",
    "collection_enabled" = EXCLUDED."collection_enabled",
    "transfer_enabled" = EXCLUDED."transfer_enabled",
    "scan_start_height" = EXCLUDED."scan_start_height",
    "scan_max_blocks_per_run" = EXCLUDED."scan_max_blocks_per_run";

INSERT INTO "public"."chain_rpc_node" ("chain", "network", "environment", "node_label", "purpose",
                                       "connection_type", "rpc_url", "auth_type", "auth_header_name",
                                       "priority", "min_request_interval_ms", "enabled", "remark",
                                       "created_at", "updated_at", "api_key")
VALUES
    ('BERACHAIN', 'bepolia', 'dev', 'official-berachain-bepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://bepolia.rpc.berachain.com', 'NONE', NULL, 10, 500, false,
     'Official Berachain Bepolia JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('BERACHAIN', 'bepolia', 'test2', 'official-berachain-bepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://bepolia.rpc.berachain.com', 'NONE', NULL, 10, 500, false,
     'test2 official Berachain Bepolia JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('BERACHAIN', 'mainnet', 'prod', 'official-berachain-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.berachain.com', 'NONE', NULL, 10, 1000, false,
     'Production Berachain mainnet JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('GNOSIS', 'chiado', 'dev', 'official-gnosis-chiado', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.chiadochain.net', 'NONE', NULL, 10, 500, false,
     'Official Gnosis Chiado JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('GNOSIS', 'chiado', 'test2', 'official-gnosis-chiado', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.chiadochain.net', 'NONE', NULL, 10, 500, false,
     'test2 official Gnosis Chiado JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('GNOSIS', 'mainnet', 'prod', 'official-gnosis-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.gnosischain.com', 'NONE', NULL, 10, 1000, false,
     'Production Gnosis mainnet JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('CELO', 'celo-sepolia', 'dev', 'official-celo-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://forno.celo-sepolia.celo-testnet.org', 'NONE', NULL, 10, 500, false,
     'Official Celo Sepolia JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('CELO', 'celo-sepolia', 'test2', 'official-celo-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://forno.celo-sepolia.celo-testnet.org', 'NONE', NULL, 10, 500, false,
     'test2 official Celo Sepolia JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('CELO', 'mainnet', 'prod', 'official-celo-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://forno.celo.org', 'NONE', NULL, 10, 1000, false,
     'Production Celo mainnet JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('MONAD', 'testnet', 'dev', 'official-monad-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testnet-rpc.monad.xyz', 'NONE', NULL, 10, 500, false,
     'Official Monad Testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('MONAD', 'testnet', 'test2', 'official-monad-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testnet-rpc.monad.xyz', 'NONE', NULL, 10, 500, false,
     'test2 official Monad Testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('MONAD', 'mainnet', 'prod', 'official-monad-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.monad.xyz', 'NONE', NULL, 10, 1000, false,
     'Production Monad mainnet JSON-RPC endpoint. EIP-7702 native collection must remain disabled because delegated EOAs cannot reduce balance below the 10 MON reserve.',
     now(), now(), NULL),
    ('WORLD_CHAIN', 'sepolia', 'dev', 'official-world-chain-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://worldchain-sepolia.g.alchemy.com/public', 'NONE', NULL, 10, 500, false,
     'Official World Chain Sepolia JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('WORLD_CHAIN', 'sepolia', 'test2', 'official-world-chain-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://worldchain-sepolia.g.alchemy.com/public', 'NONE', NULL, 10, 500, false,
     'test2 official World Chain Sepolia JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('WORLD_CHAIN', 'mainnet', 'prod', 'official-world-chain-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://worldchain-mainnet.g.alchemy.com/public', 'NONE', NULL, 10, 1000, false,
     'Production World Chain mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('INK', 'sepolia', 'dev', 'official-ink-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc-gel-sepolia.inkonchain.com', 'NONE', NULL, 10, 500, false,
     'Official Ink Sepolia JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('INK', 'sepolia', 'test2', 'official-ink-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc-gel-sepolia.inkonchain.com', 'NONE', NULL, 10, 500, false,
     'test2 official Ink Sepolia JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('INK', 'mainnet', 'prod', 'official-ink-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc-gel.inkonchain.com', 'NONE', NULL, 10, 1000, false,
     'Production Ink mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('TAIKO', 'hoodi', 'dev', 'official-taiko-hoodi', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.hoodi.taiko.xyz', 'NONE', NULL, 10, 500, false,
     'Official Taiko Hoodi JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('TAIKO', 'hoodi', 'test2', 'official-taiko-hoodi', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.hoodi.taiko.xyz', 'NONE', NULL, 10, 500, false,
     'test2 official Taiko Hoodi JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('TAIKO', 'mainnet', 'prod', 'official-taiko-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.mainnet.taiko.xyz', 'NONE', NULL, 10, 1000, false,
     'Production Taiko mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('SONEIUM', 'minato', 'dev', 'official-soneium-minato', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.minato.soneium.org', 'NONE', NULL, 10, 500, false,
     'Official Soneium Minato JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('SONEIUM', 'minato', 'test2', 'official-soneium-minato', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.minato.soneium.org', 'NONE', NULL, 10, 500, false,
     'test2 official Soneium Minato JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('SONEIUM', 'mainnet', 'prod', 'official-soneium-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.soneium.org', 'NONE', NULL, 10, 1000, false,
     'Production Soneium mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('MODE', 'sepolia', 'dev', 'official-mode-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://sepolia.mode.network', 'NONE', NULL, 10, 500, false,
     'Official Mode Sepolia JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('MODE', 'sepolia', 'test2', 'official-mode-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://sepolia.mode.network', 'NONE', NULL, 10, 500, false,
     'test2 official Mode Sepolia JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('MODE', 'mainnet', 'prod', 'official-mode-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://mainnet.mode.network', 'NONE', NULL, 10, 1000, false,
     'Production Mode mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('LISK', 'sepolia', 'dev', 'official-lisk-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.sepolia-api.lisk.com', 'NONE', NULL, 10, 500, false,
     'Official Lisk Sepolia JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('LISK', 'sepolia', 'test2', 'official-lisk-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.sepolia-api.lisk.com', 'NONE', NULL, 10, 500, false,
     'test2 official Lisk Sepolia JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('LISK', 'mainnet', 'prod', 'official-lisk-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.api.lisk.com', 'NONE', NULL, 10, 1000, false,
     'Production Lisk mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('KATANA', 'bokuto', 'dev', 'official-katana-bokuto', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc-bokuto.katanarpc.com', 'NONE', NULL, 10, 500, false,
     'Official Katana Bokuto JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('KATANA', 'bokuto', 'test2', 'official-katana-bokuto', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc-bokuto.katanarpc.com', 'NONE', NULL, 10, 500, false,
     'test2 official Katana Bokuto JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('KATANA', 'mainnet', 'prod', 'official-katana-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.katana.network', 'NONE', NULL, 10, 1000, false,
     'Production Katana mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('MEGAETH', 'carrot', 'dev', 'official-megaeth-carrot', 'rpc', 'HTTP_JSON_RPC',
     'https://carrot.megaeth.com/rpc', 'NONE', NULL, 10, 500, false,
     'Official MegaETH Carrot JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('MEGAETH', 'carrot', 'test2', 'official-megaeth-carrot', 'rpc', 'HTTP_JSON_RPC',
     'https://carrot.megaeth.com/rpc', 'NONE', NULL, 10, 500, false,
     'test2 official MegaETH Carrot JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('MEGAETH', 'mainnet', 'prod', 'official-megaeth-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://mainnet.megaeth.com/rpc', 'NONE', NULL, 10, 1000, false,
     'Production MegaETH mainnet public JSON-RPC endpoint. Use RPC gas estimation because MegaEVM gas costs differ from standard EVM.',
     now(), now(), NULL),
    ('X_LAYER', 'testnet', 'dev', 'official-x-layer-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testrpc.xlayer.tech/terigon', 'NONE', NULL, 10, 500, false,
     'Official X Layer testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('X_LAYER', 'testnet', 'test2', 'official-x-layer-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testrpc.xlayer.tech/terigon', 'NONE', NULL, 10, 500, false,
     'test2 official X Layer testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('X_LAYER', 'mainnet', 'prod', 'official-x-layer-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.xlayer.tech', 'NONE', NULL, 10, 1000, false,
     'Production X Layer mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('DEGEN', 'mainnet', 'dev', 'official-degen-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.degen.tips', 'NONE', NULL, 10, 500, false,
     'Official Degen Chain mainnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('DEGEN', 'mainnet', 'test2', 'official-degen-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.degen.tips', 'NONE', NULL, 10, 500, false,
     'test2 official Degen Chain mainnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('DEGEN', 'mainnet', 'prod', 'official-degen-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.degen.tips', 'NONE', NULL, 10, 1000, false,
     'Production Degen Chain mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('ROBINHOOD_CHAIN', 'testnet', 'dev', 'official-robinhood-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.testnet.chain.robinhood.com', 'NONE', NULL, 10, 500, false,
     'Official Robinhood Chain testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('ROBINHOOD_CHAIN', 'testnet', 'test2', 'official-robinhood-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.testnet.chain.robinhood.com', 'NONE', NULL, 10, 500, false,
     'test2 official Robinhood Chain testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('ROBINHOOD_CHAIN', 'mainnet', 'prod', 'official-robinhood-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.mainnet.chain.robinhood.com', 'NONE', NULL, 10, 1000, false,
     'Production Robinhood Chain mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('ETHERLINK', 'shadownet', 'dev', 'official-etherlink-shadownet', 'rpc', 'HTTP_JSON_RPC',
     'https://node.shadownet.etherlink.com', 'NONE', NULL, 10, 500, false,
     'Official Etherlink Shadownet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('ETHERLINK', 'shadownet', 'test2', 'official-etherlink-shadownet', 'rpc', 'HTTP_JSON_RPC',
     'https://node.shadownet.etherlink.com', 'NONE', NULL, 10, 500, false,
     'test2 official Etherlink Shadownet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('ETHERLINK', 'mainnet', 'prod', 'official-etherlink-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://node.mainnet.etherlink.com', 'NONE', NULL, 10, 1000, false,
     'Production Etherlink mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('IOTA_EVM', 'testnet', 'dev', 'official-iota-evm-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://json-rpc.evm.testnet.iotaledger.net', 'NONE', NULL, 10, 500, false,
     'Official IOTA EVM testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('IOTA_EVM', 'testnet', 'test2', 'official-iota-evm-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://json-rpc.evm.testnet.iotaledger.net', 'NONE', NULL, 10, 500, false,
     'test2 official IOTA EVM testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('IOTA_EVM', 'mainnet', 'prod', 'official-iota-evm-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://json-rpc.evm.iotaledger.net', 'NONE', NULL, 10, 1000, false,
     'Production IOTA EVM mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('OASIS_EMERALD', 'testnet', 'dev', 'official-oasis-emerald-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testnet.emerald.oasis.io', 'NONE', NULL, 10, 500, false,
     'Official Oasis Emerald testnet Web3 gateway. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('OASIS_EMERALD', 'testnet', 'test2', 'official-oasis-emerald-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testnet.emerald.oasis.io', 'NONE', NULL, 10, 500, false,
     'test2 official Oasis Emerald testnet Web3 gateway. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('OASIS_EMERALD', 'mainnet', 'prod', 'official-oasis-emerald-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://emerald.oasis.io', 'NONE', NULL, 10, 1000, false,
     'Production Oasis Emerald mainnet Web3 gateway. Enable only after private gateway, funding and monitoring are ready.',
     now(), now(), NULL),
    ('CRONOS', 'testnet', 'dev', 'official-cronos-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://evm-t3.cronos.org', 'NONE', NULL, 10, 500, false,
     'Official Cronos EVM testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('CRONOS', 'testnet', 'test2', 'official-cronos-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://evm-t3.cronos.org', 'NONE', NULL, 10, 500, false,
     'test2 official Cronos EVM testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('CRONOS', 'mainnet', 'prod', 'official-cronos-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://evm.cronos.org', 'NONE', NULL, 10, 1000, false,
     'Production Cronos EVM mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('SONIC', 'testnet', 'dev', 'official-sonic-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.testnet.soniclabs.com', 'NONE', NULL, 10, 500, false,
     'Official Sonic testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('SONIC', 'testnet', 'test2', 'official-sonic-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.testnet.soniclabs.com', 'NONE', NULL, 10, 500, false,
     'test2 official Sonic testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('SONIC', 'mainnet', 'prod', 'official-sonic-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.soniclabs.com', 'NONE', NULL, 10, 1000, false,
     'Production Sonic mainnet public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('PULSECHAIN', 'testnet', 'dev', 'official-pulsechain-testnet-v4', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.v4.testnet.pulsechain.com', 'NONE', NULL, 10, 1000, false,
     'Official PulseChain testnet v4 JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('PULSECHAIN', 'testnet', 'test2', 'official-pulsechain-testnet-v4', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.v4.testnet.pulsechain.com', 'NONE', NULL, 10, 1000, false,
     'test2 official PulseChain testnet v4 JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('PULSECHAIN', 'mainnet', 'prod', 'official-pulsechain-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.pulsechain.com', 'NONE', NULL, 10, 1000, false,
     'Production PulseChain public JSON-RPC can be unstable. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('ZETACHAIN', 'testnet', 'dev', 'blockpi-zetachain-athens', 'rpc', 'HTTP_JSON_RPC',
     'https://zetachain-athens-evm.blockpi.network/v1/rpc/public', 'NONE', NULL, 10, 1000, false,
     'ZetaChain Athens EVM JSON-RPC endpoint. Stablecoin ZRC-20 assets are paused on Athens; local tests use Hardhat.',
     now(), now(), NULL),
    ('ZETACHAIN', 'testnet', 'test2', 'blockpi-zetachain-athens', 'rpc', 'HTTP_JSON_RPC',
     'https://zetachain-athens-evm.blockpi.network/v1/rpc/public', 'NONE', NULL, 10, 1000, false,
     'test2 ZetaChain Athens EVM JSON-RPC endpoint. Enable only for explicit native ZETA live tests.',
     now(), now(), NULL),
    ('ZETACHAIN', 'mainnet', 'prod', 'blockpi-zetachain-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://zetachain-evm.blockpi.network/v1/rpc/public', 'NONE', NULL, 10, 1000, false,
     'Production ZetaChain public EVM JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('CORE', 'testnet', 'dev', 'official-core-testnet2', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.test2.btcs.network', 'NONE', NULL, 10, 500, false,
     'Official Core Testnet2 JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('CORE', 'testnet', 'test2', 'official-core-testnet2', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.test2.btcs.network', 'NONE', NULL, 10, 500, false,
     'test2 official Core Testnet2 JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('CORE', 'mainnet', 'prod', 'official-core-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.coredao.org', 'NONE', NULL, 10, 1000, false,
     'Production Core public JSON-RPC can have transient TLS failures. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('SOMNIA', 'testnet', 'dev', 'official-somnia-shannon', 'rpc', 'HTTP_JSON_RPC',
     'https://dream-rpc.somnia.network', 'NONE', NULL, 10, 500, false,
     'Official Somnia Shannon JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('SOMNIA', 'testnet', 'test2', 'official-somnia-shannon', 'rpc', 'HTTP_JSON_RPC',
     'https://dream-rpc.somnia.network', 'NONE', NULL, 10, 500, false,
     'test2 official Somnia Shannon JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('SOMNIA', 'mainnet', 'prod', 'official-somnia-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://api.infra.mainnet.somnia.network', 'NONE', NULL, 10, 1000, false,
     'Production Somnia public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('RONIN', 'testnet', 'dev', 'official-ronin-saigon', 'rpc', 'HTTP_JSON_RPC',
     'https://saigon-testnet.roninchain.com/rpc', 'NONE', NULL, 10, 500, false,
     'Official Ronin Saigon JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('RONIN', 'testnet', 'test2', 'official-ronin-saigon', 'rpc', 'HTTP_JSON_RPC',
     'https://saigon-testnet.roninchain.com/rpc', 'NONE', NULL, 10, 500, false,
     'test2 official Ronin Saigon JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('RONIN', 'mainnet', 'prod', 'official-ronin-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://api.roninchain.com/rpc', 'NONE', NULL, 10, 1000, false,
     'Production Ronin public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('CHILIZ', 'testnet', 'dev', 'official-chiliz-spicy', 'rpc', 'HTTP_JSON_RPC',
     'https://spicy-rpc.chiliz.com/', 'NONE', NULL, 10, 500, false,
     'Official Chiliz Spicy JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('CHILIZ', 'testnet', 'test2', 'official-chiliz-spicy', 'rpc', 'HTTP_JSON_RPC',
     'https://spicy-rpc.chiliz.com/', 'NONE', NULL, 10, 500, false,
     'test2 official Chiliz Spicy JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('CHILIZ', 'mainnet', 'prod', 'official-listed-chiliz-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://chiliz-rpc.publicnode.com', 'NONE', NULL, 10, 1000, false,
     'Production Chiliz public JSON-RPC endpoint listed by official docs. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('IOTEX', 'testnet', 'dev', 'official-iotex-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://babel-api.testnet.iotex.io', 'NONE', NULL, 10, 500, false,
     'Official IoTeX testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('IOTEX', 'testnet', 'test2', 'official-iotex-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://babel-api.testnet.iotex.io', 'NONE', NULL, 10, 500, false,
     'test2 official IoTeX JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('IOTEX', 'mainnet', 'prod', 'official-iotex-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://babel-api.mainnet.iotex.io', 'NONE', NULL, 10, 1000, false,
     'Production IoTeX public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('KAIA', 'testnet', 'dev', 'official-kaia-kairos', 'rpc', 'HTTP_JSON_RPC',
     'https://public-en-kairos.node.kaia.io', 'NONE', NULL, 10, 500, false,
     'Official Kaia Kairos JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('KAIA', 'testnet', 'test2', 'official-kaia-kairos', 'rpc', 'HTTP_JSON_RPC',
     'https://public-en-kairos.node.kaia.io', 'NONE', NULL, 10, 500, false,
     'test2 official Kaia Kairos JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('KAIA', 'mainnet', 'prod', 'official-kaia-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://public-en.node.kaia.io', 'NONE', NULL, 10, 1000, false,
     'Production Kaia public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('PLASMA', 'testnet', 'dev', 'official-plasma-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testnet-rpc.plasma.to', 'NONE', NULL, 10, 500, false,
     'Official Plasma testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('PLASMA', 'testnet', 'test2', 'official-plasma-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://testnet-rpc.plasma.to', 'NONE', NULL, 10, 500, false,
     'test2 official Plasma testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('PLASMA', 'mainnet', 'prod', 'official-plasma-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.plasma.to', 'NONE', NULL, 10, 1000, false,
     'Production Plasma public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('STORY', 'testnet', 'dev', 'official-story-aeneid', 'rpc', 'HTTP_JSON_RPC',
     'https://aeneid.storyrpc.io', 'NONE', NULL, 10, 500, false,
     'Official Story Aeneid JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('STORY', 'testnet', 'test2', 'official-story-aeneid', 'rpc', 'HTTP_JSON_RPC',
     'https://aeneid.storyrpc.io', 'NONE', NULL, 10, 500, false,
     'test2 official Story Aeneid JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('STORY', 'mainnet', 'prod', 'official-story-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://mainnet.storyrpc.io', 'NONE', NULL, 10, 1000, false,
     'Production Story public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('SEI', 'testnet', 'dev', 'official-sei-atlantic-2', 'rpc', 'HTTP_JSON_RPC',
     'https://evm-rpc-testnet.sei-apis.com', 'NONE', NULL, 10, 500, false,
     'Official Sei Atlantic-2 EVM JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('SEI', 'testnet', 'test2', 'official-sei-atlantic-2', 'rpc', 'HTTP_JSON_RPC',
     'https://evm-rpc-testnet.sei-apis.com', 'NONE', NULL, 10, 500, false,
     'test2 official Sei Atlantic-2 EVM JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('SEI', 'mainnet', 'prod', 'official-sei-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://evm-rpc.sei-apis.com', 'NONE', NULL, 10, 1000, false,
     'Production Sei public EVM JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('CONFLUX', 'testnet', 'dev', 'official-conflux-espace-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://evmtestnet.confluxrpc.com', 'NONE', NULL, 10, 1250, false,
     'Official Conflux eSpace testnet JSON-RPC endpoint. Disabled by default; local tests use Hardhat.',
     now(), now(), NULL),
    ('CONFLUX', 'testnet', 'test2', 'official-conflux-espace-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://evmtestnet.confluxrpc.com', 'NONE', NULL, 10, 1250, false,
     'test2 official Conflux eSpace testnet JSON-RPC endpoint. Enable only for explicit live tests.',
     now(), now(), NULL),
    ('CONFLUX', 'mainnet', 'prod', 'official-conflux-espace-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://evm.confluxrpc.com', 'NONE', NULL, 10, 1250, false,
     'Production Conflux eSpace public JSON-RPC endpoint. Enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('VECTOR_SMART_CHAIN', 'mainnet', 'prod', 'official-vector-smart-chain-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://rpc.vscblockchain.org', 'NONE', NULL, 10, 5500, false,
     'Production Vector Smart Chain public JSON-RPC endpoint. No verified public testnet; enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL),
    ('KROWN', 'mainnet', 'prod', 'official-krown-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://mainnet.krown.network', 'NONE', NULL, 10, 6000, false,
     'Production Krown public JSON-RPC endpoint. No verified public testnet; enable only after private RPC, funding and monitoring are ready.',
     now(), now(), NULL)
ON CONFLICT ("chain", "network", "environment", "purpose", "node_label") DO UPDATE SET
    "connection_type" = EXCLUDED."connection_type",
    "rpc_url" = EXCLUDED."rpc_url",
    "auth_type" = EXCLUDED."auth_type",
    "auth_header_name" = EXCLUDED."auth_header_name",
    "api_key" = EXCLUDED."api_key",
    "priority" = EXCLUDED."priority",
    "min_request_interval_ms" = EXCLUDED."min_request_interval_ms",
    "enabled" = EXCLUDED."enabled",
    "remark" = EXCLUDED."remark",
    "updated_at" = now();


COMMIT;
