-- 同步 Starknet、zkSync Era 与 OKT Chain 的链配置。
-- zkSync Era 使用官方 ETH/USDC 配置；OKT Chain 仅保留历史资产和关闭的配置，
-- 因官方已提示链将停止运营，任何生产启用都必须先完成独立的生命周期与资产可恢复性确认。
-- Starknet 同时增加账户交易审计表和 chain_profile.account_class_hash 字段。
-- 本迁移只增加配置，不修改业务数据；可重复执行。

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('surprising-wallet:20260802:zksync-okt-chain-config'));

ALTER TABLE public.evm_token_transfer
    ADD COLUMN IF NOT EXISTS raw_payload text;

ALTER TABLE public.chain_profile
    ADD COLUMN IF NOT EXISTS account_class_hash character varying(128);

CREATE TABLE IF NOT EXISTS public.starknet_transaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain character varying(32) NOT NULL,
    tx_hash character varying(128) NOT NULL,
    from_address character varying(160),
    to_address character varying(160) NOT NULL,
    asset_symbol character varying(32) NOT NULL,
    contract_address character varying(128),
    amount numeric(78,18) DEFAULT 0 NOT NULL,
    fee numeric(78,18) DEFAULT 0 NOT NULL,
    block_height bigint,
    confirmations integer DEFAULT 0 NOT NULL,
    status character varying(32) DEFAULT 'CREATED' NOT NULL,
    raw_payload text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT starknet_transaction_chain_tx_hash_key UNIQUE (chain, tx_hash)
);

INSERT INTO public.chain_asset (
    chain, symbol, asset_kind, contract_address, decimals, native_asset, active,
    min_transfer, min_withdraw, created_at, updated_at)
VALUES
    ('STARKNET', 'STRK', 'NATIVE',
     '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d',
     18, true, true, 0.000001, 0.000001, now(), now()),
    ('STARKNET', 'USDC', 'ERC20',
     '0x0512feAc6339Ff7889822cb5aA2a86C848e9D392bB0E3E237C008674feeD8343',
     6, false, false, 1, 1, now(), now())
ON CONFLICT (chain, symbol) DO UPDATE SET
    contract_address = EXCLUDED.contract_address,
    decimals = EXCLUDED.decimals,
    active = EXCLUDED.active,
    updated_at = now();

INSERT INTO public.token_config (
    chain, symbol, standard, contract_address, decimals, enabled,
    min_deposit, min_withdraw, collect_enabled, created_at, updated_at,
    network, token_standard, min_deposit_amount, min_withdraw_amount,
    collect_threshold, gas_strategy, confirmation_required)
VALUES
    ('STARKNET', 'USDC', 'ERC20',
     '0x033068F6539f8e6e6b131e6B2B814e6c34A5224bC66947c47DaB9dFeE93b35fb',
     6, false, 1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('STARKNET', 'USDC', 'ERC20',
     '0x0512feAc6339Ff7889822cb5aA2a86C848e9D392bB0E3E237C008674feeD8343',
     6, false, 1, 1, true, now(), now(), 'sepolia', 'ERC20', 1, 1, 1, 'native-gas', 1)
ON CONFLICT (chain, network, symbol) DO UPDATE SET
    contract_address = EXCLUDED.contract_address,
    decimals = EXCLUDED.decimals,
    enabled = EXCLUDED.enabled,
    updated_at = now();

INSERT INTO public.chain_profile (
    chain, network, family, runtime_currency_id, bip44_coin_type, native_symbol,
    rpc_url, explorer_url, deposit_confirmations, withdraw_confirmations,
    default_fee_rate, dust_threshold, enabled, created_at, updated_at, chain_id,
    account_class_hash, gas_policy, scan_batch_size, scan_enabled, withdraw_enabled,
    collection_enabled, transfer_enabled, scan_start_height, scan_max_blocks_per_run)
VALUES
    ('STARKNET', 'sepolia', 'starknet', 9046, 9004, 'STRK',
     'https://alpha-sepolia.starknet.io/rpc/v0_8', 'https://sepolia.voyager.online/tx/',
     12, 12, 1000000000000000, 0, false, now(), now(), NULL, NULL, NULL, 100,
     false, false, false, false, 0, 100),
    ('STARKNET', 'mainnet', 'starknet', 9046, 9004, 'STRK',
     'https://alpha-mainnet.starknet.io/rpc/v0_8', 'https://voyager.online/tx/',
     24, 24, 1000000000000000, 0, false, now(), now(), NULL, NULL, NULL, 100,
     false, false, false, false, 0, 100)
ON CONFLICT (chain, network) DO UPDATE SET
    family = EXCLUDED.family,
    runtime_currency_id = EXCLUDED.runtime_currency_id,
    bip44_coin_type = EXCLUDED.bip44_coin_type,
    native_symbol = EXCLUDED.native_symbol,
    rpc_url = EXCLUDED.rpc_url,
    explorer_url = EXCLUDED.explorer_url,
    deposit_confirmations = EXCLUDED.deposit_confirmations,
    withdraw_confirmations = EXCLUDED.withdraw_confirmations,
    default_fee_rate = EXCLUDED.default_fee_rate,
    dust_threshold = EXCLUDED.dust_threshold,
    enabled = EXCLUDED.enabled,
    updated_at = now(),
    account_class_hash = EXCLUDED.account_class_hash,
    scan_batch_size = EXCLUDED.scan_batch_size,
    scan_enabled = EXCLUDED.scan_enabled,
    withdraw_enabled = EXCLUDED.withdraw_enabled,
    collection_enabled = EXCLUDED.collection_enabled,
    transfer_enabled = EXCLUDED.transfer_enabled,
    scan_start_height = EXCLUDED.scan_start_height,
    scan_max_blocks_per_run = EXCLUDED.scan_max_blocks_per_run;

INSERT INTO public.chain_rpc_node (
    chain, network, environment, node_label, purpose, connection_type, rpc_url,
    auth_type, auth_header_name, priority, min_request_interval_ms, enabled,
    remark, created_at, updated_at, api_key)
VALUES
    ('STARKNET', 'sepolia', 'dev', 'official-starknet-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://alpha-sepolia.starknet.io/rpc/v0_8', 'NONE', NULL, 10, 500, false,
     'Starknet Sepolia RPC; configure a provider/API key before enabling.', now(), now(), NULL),
    ('STARKNET', 'sepolia', 'dev', 'official-starknet-sepolia', 'scan', 'HTTP_JSON_RPC',
     'https://alpha-sepolia.starknet.io/rpc/v0_8', 'NONE', NULL, 10, 500, false,
     'Starknet Sepolia event scanner RPC; configure a provider/API key before enabling.', now(), now(), NULL),
    ('STARKNET', 'sepolia', 'dev', 'official-starknet-sepolia', 'broadcast', 'HTTP_JSON_RPC',
     'https://alpha-sepolia.starknet.io/rpc/v0_8', 'NONE', NULL, 10, 500, false,
     'Starknet Sepolia transaction RPC; configure a provider/API key before enabling.', now(), now(), NULL),
    ('STARKNET', 'mainnet', 'prod', 'official-starknet-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://alpha-mainnet.starknet.io/rpc/v0_8', 'NONE', NULL, 10, 1000, false,
     'Starknet mainnet RPC; keep disabled until class hash and provider are approved.', now(), now(), NULL),
    ('STARKNET', 'mainnet', 'prod', 'official-starknet-mainnet', 'scan', 'HTTP_JSON_RPC',
     'https://alpha-mainnet.starknet.io/rpc/v0_8', 'NONE', NULL, 10, 1000, false,
     'Starknet mainnet event scanner RPC; keep disabled until provider is approved.', now(), now(), NULL),
    ('STARKNET', 'mainnet', 'prod', 'official-starknet-mainnet', 'broadcast', 'HTTP_JSON_RPC',
     'https://alpha-mainnet.starknet.io/rpc/v0_8', 'NONE', NULL, 10, 1000, false,
     'Starknet mainnet transaction RPC; keep disabled until provider is approved.', now(), now(), NULL)
ON CONFLICT (chain, network, environment, purpose, node_label) DO UPDATE SET
    rpc_url = EXCLUDED.rpc_url,
    enabled = EXCLUDED.enabled,
    remark = EXCLUDED.remark,
    updated_at = now();

INSERT INTO public.chain_asset (
    chain, symbol, asset_kind, contract_address, decimals, native_asset, active,
    min_transfer, min_withdraw, created_at, updated_at
)
VALUES
    ('ZKSYNC', 'ETH_ZKSYNC', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('ZKSYNC', 'USDC', 'ERC20', '0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4', 6, false, true, 1, 1, now(), now()),
    ('OKT_CHAIN', 'OKT', 'NATIVE', NULL, 18, true, true, 0.000001, 0.000001, now(), now()),
    ('OKT_CHAIN', 'USDT', 'KIP20', '0x382bB369d343125BfB2117af9c149795C6C65C50', 6, false, true, 1, 1, now(), now())
ON CONFLICT (chain, symbol) DO UPDATE SET
    asset_kind = EXCLUDED.asset_kind,
    contract_address = EXCLUDED.contract_address,
    decimals = EXCLUDED.decimals,
    native_asset = EXCLUDED.native_asset,
    active = EXCLUDED.active,
    min_transfer = EXCLUDED.min_transfer,
    min_withdraw = EXCLUDED.min_withdraw,
    updated_at = now();

INSERT INTO public.token_config (
    chain, symbol, standard, contract_address, decimals, enabled,
    min_deposit, min_withdraw, collect_enabled, created_at, updated_at,
    network, token_standard, min_deposit_amount, min_withdraw_amount,
    collect_threshold, gas_strategy, confirmation_required
)
VALUES
    ('ZKSYNC', 'USDC', 'ERC20', '0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('ZKSYNC', 'USDC', 'ERC20', '0xAe045DE5638162fa134807Cb558E15A3F5A7F853', 6, true,
     1, 1, true, now(), now(), 'sepolia', 'ERC20', 1, 1, 1, 'native-gas', 1),
    ('OKT_CHAIN', 'USDT', 'KIP20', '0x382bB369d343125BfB2117af9c149795C6C65C50', 6, false,
     1, 1, true, now(), now(), 'mainnet', 'KIP20', 1, 1, 1, 'native-gas', 1)
ON CONFLICT (chain, network, symbol) DO UPDATE SET
    standard = EXCLUDED.standard,
    contract_address = EXCLUDED.contract_address,
    decimals = EXCLUDED.decimals,
    enabled = EXCLUDED.enabled,
    min_deposit = EXCLUDED.min_deposit,
    min_withdraw = EXCLUDED.min_withdraw,
    collect_enabled = EXCLUDED.collect_enabled,
    token_standard = EXCLUDED.token_standard,
    min_deposit_amount = EXCLUDED.min_deposit_amount,
    min_withdraw_amount = EXCLUDED.min_withdraw_amount,
    collect_threshold = EXCLUDED.collect_threshold,
    gas_strategy = EXCLUDED.gas_strategy,
    confirmation_required = EXCLUDED.confirmation_required,
    updated_at = now();

INSERT INTO public.chain_profile (
    chain, network, family, runtime_currency_id, bip44_coin_type, native_symbol,
    rpc_url, explorer_url, deposit_confirmations, withdraw_confirmations,
    default_fee_rate, dust_threshold, enabled, created_at, updated_at, chain_id,
    gas_policy, scan_batch_size, scan_enabled, withdraw_enabled, collection_enabled,
    transfer_enabled, scan_start_height, scan_max_blocks_per_run
)
VALUES
    ('ZKSYNC', 'sepolia', 'evm', 9044, 60, 'ETH_ZKSYNC',
     'https://sepolia.era.zksync.dev', 'https://sepolia.explorer.zksync.io/tx/',
     40, 40, 1, 0, false, now(), now(), 300, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('ZKSYNC', 'mainnet', 'evm', 9044, 60, 'ETH_ZKSYNC',
     'https://mainnet.era.zksync.io', 'https://explorer.zksync.io/tx/',
     40, 40, 1, 0, false, now(), now(), 324, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('OKT_CHAIN', 'testnet', 'evm', 9045, 60, 'OKT',
     'https://exchaintestrpc.okex.org', 'https://www.oklink.com/oktc/tx/',
     40, 40, 1, 0, false, now(), now(), 65, 'eip1559', 200,
     false, false, false, false, 0, 200),
    ('OKT_CHAIN', 'mainnet', 'evm', 9045, 60, 'OKT',
     'https://exchainrpc.okex.org', 'https://www.oklink.com/oktc/tx/',
     40, 40, 1, 0, false, now(), now(), 66, 'eip1559', 200,
     false, false, false, false, 0, 200)
ON CONFLICT (chain, network) DO UPDATE SET
    family = EXCLUDED.family,
    runtime_currency_id = EXCLUDED.runtime_currency_id,
    bip44_coin_type = EXCLUDED.bip44_coin_type,
    native_symbol = EXCLUDED.native_symbol,
    rpc_url = EXCLUDED.rpc_url,
    explorer_url = EXCLUDED.explorer_url,
    deposit_confirmations = EXCLUDED.deposit_confirmations,
    withdraw_confirmations = EXCLUDED.withdraw_confirmations,
    default_fee_rate = EXCLUDED.default_fee_rate,
    dust_threshold = EXCLUDED.dust_threshold,
    enabled = EXCLUDED.enabled,
    updated_at = now(),
    chain_id = EXCLUDED.chain_id,
    gas_policy = EXCLUDED.gas_policy,
    scan_batch_size = EXCLUDED.scan_batch_size,
    scan_enabled = EXCLUDED.scan_enabled,
    withdraw_enabled = EXCLUDED.withdraw_enabled,
    collection_enabled = EXCLUDED.collection_enabled,
    transfer_enabled = EXCLUDED.transfer_enabled,
    scan_start_height = EXCLUDED.scan_start_height,
    scan_max_blocks_per_run = EXCLUDED.scan_max_blocks_per_run;

INSERT INTO public.chain_rpc_node (
    chain, network, environment, node_label, purpose, connection_type,
    rpc_url, auth_type, auth_header_name, priority, min_request_interval_ms,
    enabled, remark, created_at, updated_at, api_key
)
VALUES
    ('ZKSYNC', 'sepolia', 'dev', 'official-zksync-sepolia', 'rpc', 'HTTP_JSON_RPC',
     'https://sepolia.era.zksync.dev', 'NONE', NULL, 10, 500, false,
     'Official zkSync Era Sepolia JSON-RPC endpoint; local tests use Hardhat.', now(), now(), NULL),
    ('ZKSYNC', 'mainnet', 'prod', 'official-zksync-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://mainnet.era.zksync.io', 'NONE', NULL, 10, 1000, false,
     'Official zkSync Era mainnet JSON-RPC endpoint; enable only after production readiness review.', now(), now(), NULL),
    ('OKT_CHAIN', 'testnet', 'dev', 'historical-okt-chain-testnet', 'rpc', 'HTTP_JSON_RPC',
     'https://exchaintestrpc.okex.org', 'NONE', NULL, 10, 500, false,
     'Historical OKT Chain testnet endpoint; disabled because chain operations are being discontinued.', now(), now(), NULL),
    ('OKT_CHAIN', 'mainnet', 'prod', 'historical-okt-chain-mainnet', 'rpc', 'HTTP_JSON_RPC',
     'https://exchainrpc.okex.org', 'NONE', NULL, 10, 1000, false,
     'Historical OKT Chain mainnet endpoint; keep disabled until lifecycle and asset recovery are confirmed.', now(), now(), NULL)
ON CONFLICT (chain, network, environment, purpose, node_label) DO UPDATE SET
    connection_type = EXCLUDED.connection_type,
    rpc_url = EXCLUDED.rpc_url,
    auth_type = EXCLUDED.auth_type,
    auth_header_name = EXCLUDED.auth_header_name,
    api_key = EXCLUDED.api_key,
    priority = EXCLUDED.priority,
    min_request_interval_ms = EXCLUDED.min_request_interval_ms,
    enabled = EXCLUDED.enabled,
    remark = EXCLUDED.remark,
    updated_at = now();

COMMIT;
