#!/usr/bin/env bash
set -euo pipefail

TON_FLOW_ROOT=$(git rev-parse --show-toplevel)
source "$TON_FLOW_ROOT/scripts/regtest/local-postgres.sh"
TON_FLOW_DB="surprising_wallet_test_ton_$$"
TON_FLOW_STACK="surprising-wallet-ton-$$"
TON_FLOW_NETWORK="${TON_FLOW_STACK}-network"
TON_FLOW_SHARED_VOLUME="${TON_FLOW_STACK}-shared"
TON_FLOW_CHAIN_VOLUME="${TON_FLOW_STACK}-chain"
TON_FLOW_GENESIS_CONTAINER="${TON_FLOW_STACK}-genesis"
TON_FLOW_API_CONTAINER="${TON_FLOW_STACK}-api"
TON_FLOW_FAUCET_CONTAINER="${TON_FLOW_STACK}-faucet"
TON_FLOW_RPC_PORT=${TON_FLOW_RPC_PORT:-18082}
TON_FLOW_FAUCET_PORT=${TON_FLOW_FAUCET_PORT:-18088}
TON_FLOW_RPC_URL="http://127.0.0.1:${TON_FLOW_RPC_PORT}"
TON_FLOW_FAUCET_URL="http://127.0.0.1:${TON_FLOW_FAUCET_PORT}"
TON_FLOW_GENESIS_IMAGE='ghcr.io/neodix42/mylocalton-docker@sha256:d1fbed5c9cde7e5b79817246d5ef2fc663203b052eed332766e79781e6f38f3b'
TON_FLOW_API_IMAGE='toncenter/ton-http-api@sha256:a7ad5492ac9ce98e8cbc918ff1e8a6222a31602a1b0924a349eb11246b9af474'
TON_FLOW_FAUCET_IMAGE='ghcr.io/neodix42/mylocalton-docker-faucet@sha256:f97fa83aeb53dbb5e3de621fa504797cd2c5722ec79839866a0f7cc35e5277b0'
TON_TEST_MASTER_SEED=${TON_TEST_MASTER_SEED:-000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f}
TON_TEST_SOURCE_ADDRESS=0QBi-S8V1mNK01lqxSNfYUQk3pX3ays7bbjYqgAG1SpHOjkS

cleanup() {
  local status=$?
  trap - EXIT INT TERM
  local_pg_drop "$TON_FLOW_DB" >/dev/null 2>&1 || true
  docker rm -f "$TON_FLOW_FAUCET_CONTAINER" "$TON_FLOW_API_CONTAINER" \
    "$TON_FLOW_GENESIS_CONTAINER" >/dev/null 2>&1 || true
  docker network rm "$TON_FLOW_NETWORK" >/dev/null 2>&1 || true
  docker volume rm "$TON_FLOW_SHARED_VOLUME" "$TON_FLOW_CHAIN_VOLUME" >/dev/null 2>&1 || true
  exit "$status"
}
trap cleanup EXIT INT TERM

for command in curl docker git jq mvn; do
  command -v "$command" >/dev/null || {
    printf 'missing required command: %s\n' "$command" >&2
    exit 1
  }
done

docker info >/dev/null || {
  printf 'Docker daemon is not available\n' >&2
  exit 1
}

for image in "$TON_FLOW_GENESIS_IMAGE" "$TON_FLOW_API_IMAGE" "$TON_FLOW_FAUCET_IMAGE"; do
  docker image inspect "$image" >/dev/null 2>&1 || docker pull "$image"
done

docker network create "$TON_FLOW_NETWORK" >/dev/null
docker volume create "$TON_FLOW_SHARED_VOLUME" >/dev/null
docker volume create "$TON_FLOW_CHAIN_VOLUME" >/dev/null

docker run -d --name "$TON_FLOW_GENESIS_CONTAINER" \
  --network "$TON_FLOW_NETWORK" \
  -v "$TON_FLOW_SHARED_VOLUME:/usr/share/data" \
  -v "$TON_FLOW_CHAIN_VOLUME:/var/ton-work/db" \
  -e GENESIS=true \
  -e NAME=genesis \
  -e NEXT_BLOCK_GENERATION_DELAY=2 \
  -e VALIDATION_PERIOD=1200 \
  -e MASTERCHAIN_ONLY=false \
  -e VERBOSITY=1 \
  -e GLOBAL_ID=-217 \
  -e MIN_VALIDATORS=1 \
  -e SIMPLE_FAUCET_INITIAL_BALANCE=1000000 \
  -e HIGHLOAD_FAUCET_INITIAL_BALANCE=1000000 \
  "$TON_FLOW_GENESIS_IMAGE" >/dev/null

genesis_ready=false
for attempt in {1..60}; do
  if docker exec "$TON_FLOW_GENESIS_CONTAINER" /usr/local/bin/lite-client \
    -a 127.0.0.1:40004 -p /var/ton-work/db/liteserver.pub -t 3 -c last \
    >/dev/null 2>&1; then
    genesis_ready=true
    break
  fi
  sleep 1
done
if [[ "$genesis_ready" != true ]]; then
  docker logs --tail 160 "$TON_FLOW_GENESIS_CONTAINER" >&2
  printf 'MyLocalTon genesis did not become ready\n' >&2
  exit 1
fi

# The Python HTTP API loads the exact tonlib generated by this genesis image. This avoids
# protocol drift between the independently released C++ API image and MyLocalTon latest.
docker run -d --name "$TON_FLOW_API_CONTAINER" \
  --network "$TON_FLOW_NETWORK" \
  -p "127.0.0.1:${TON_FLOW_RPC_PORT}:8081" \
  -v "$TON_FLOW_SHARED_VOLUME:/usr/share/data" \
  -e TON_API_TONLIB_LITESERVER_CONFIG=/usr/share/data/global.config.json \
  -e TON_API_TONLIB_CDLL_PATH=/usr/share/data/libtonlibjson.so \
  -e TON_API_TONLIB_KEYSTORE=/tmp/ton_keystore \
  -e TON_API_CACHE_ENABLED=0 \
  -e TON_API_WEBSERVERS_WORKERS=1 \
  -e TON_API_LOGS_LEVEL=WARNING \
  "$TON_FLOW_API_IMAGE" >/dev/null

api_ready=false
for attempt in {1..60}; do
  if curl -fsS --max-time 5 "$TON_FLOW_RPC_URL/getMasterchainInfo" \
    | jq -e '.ok == true' >/dev/null 2>&1; then
    api_ready=true
    break
  fi
  sleep 1
done
if [[ "$api_ready" != true ]]; then
  docker logs --tail 160 "$TON_FLOW_API_CONTAINER" >&2
  printf 'TON HTTP API did not become ready at %s\n' "$TON_FLOW_RPC_URL" >&2
  exit 1
fi

docker run -d --name "$TON_FLOW_FAUCET_CONTAINER" \
  --network "$TON_FLOW_NETWORK" \
  -p "127.0.0.1:${TON_FLOW_FAUCET_PORT}:88" \
  -v "$TON_FLOW_SHARED_VOLUME:/usr/share/data" \
  -e SERVER_PORT=88 \
  -e FAUCET_USE_RECAPTCHA=false \
  -e RECAPTCHA_SITE_KEY=disabled \
  -e RECAPTCHA_SECRET=disabled \
  -e FAUCET_SINGLE_GIVEAWAY=25 \
  -e FAUCET_REQUEST_EXPIRATION_PERIOD=5 \
  -e MASTERCHAIN_ONLY=false \
  "$TON_FLOW_FAUCET_IMAGE" >/dev/null

faucet_ready=false
for attempt in {1..60}; do
  if curl -fsS --max-time 5 "$TON_FLOW_FAUCET_URL/" >/dev/null 2>&1; then
    faucet_ready=true
    break
  fi
  sleep 1
done
if [[ "$faucet_ready" != true ]]; then
  docker logs --tail 160 "$TON_FLOW_FAUCET_CONTAINER" >&2
  printf 'MyLocalTon faucet did not become ready at %s\n' "$TON_FLOW_FAUCET_URL" >&2
  exit 1
fi

curl -fsS --max-time 10 -X POST "$TON_FLOW_FAUCET_URL/requestGrams" \
  -H 'content-type: application/json' \
  -d "{\"userAddress1\":\"$TON_TEST_SOURCE_ADDRESS\"}" \
  | jq -e '.success == "true" or .success == true' >/dev/null

source_balance=0
for attempt in {1..120}; do
  payload=$(curl -sS --max-time 5 --get "$TON_FLOW_RPC_URL/getAddressBalance" \
    --data-urlencode "address=$TON_TEST_SOURCE_ADDRESS" || true)
  source_balance=$(printf '%s' "$payload" \
    | jq -er 'select(.ok == true) | .result | tonumber' 2>/dev/null || printf '0')
  if (( source_balance > 16000000000 )); then
    break
  fi
  sleep 1
done
docker rm -f "$TON_FLOW_FAUCET_CONTAINER" >/dev/null 2>&1 || true
if (( source_balance <= 16000000000 )); then
  printf 'MyLocalTon faucet did not fund deterministic source %s\n' \
    "$TON_TEST_SOURCE_ADDRESS" >&2
  exit 1
fi

local_pg_require
local_pg_create "$TON_FLOW_DB"
TON_FLOW_DB_URL=$(local_pg_jdbc_url "$TON_FLOW_DB")

curl -fsS --max-time 10 "$TON_FLOW_RPC_URL/getMasterchainInfo" \
  | jq -e '.ok == true' >/dev/null || {
    printf 'TON HTTP API is not ready at %s\n' "$TON_FLOW_RPC_URL" >&2
    exit 1
  }

local_pg_psql "$TON_FLOW_DB" -v ON_ERROR_STOP=1 -q \
  -f "$TON_FLOW_ROOT/docs/db/surprising-wallet-init-pgsql.sql"

SW_ED25519_SEED="$TON_TEST_MASTER_SEED" \
TON_DB_URL="$TON_FLOW_DB_URL" \
TON_DB_USER="$REGTEST_PG_USER" \
TON_DB_PASSWORD="$REGTEST_PG_PASSWORD" \
TON_RPC_URL="$TON_FLOW_RPC_URL" \
mvn -f "$TON_FLOW_ROOT/pom.xml" \
  -pl backendservices/wallet-parent/wallet-service -am \
  -Dtest=TonCenterClientTest,TonDatabaseFlowIntegrationTest,TonLocalFundingIntegrationTest,TonLiveMockJettonFlowIntegrationTest \
  -Dsurefire.failIfNoSpecifiedTests=false \
  -Dton.db.enabled=true \
  -Dton.local.funding.enabled=true \
  -Dton.live.enabled=true \
  test

local_pg_psql "$TON_FLOW_DB" -v ON_ERROR_STOP=1 -Atqc "
do \$\$
begin
  if (select count(*) from deposit_record where chain='TON' and status='CREDITED'
      and asset_symbol in ('TON','USDT','USDC')) < 3 then
    raise exception 'expected credited TON, USDT, and USDC deposits';
  end if;
  if (select count(*) from withdrawal_order where chain='TON' and status='CONFIRMED'
      and asset_symbol in ('TON','USDT','USDC')) <> 3 then
    raise exception 'expected confirmed TON, USDT, and USDC withdrawals';
  end if;
  if (select count(*) from collection_record where chain='TON' and status='CONFIRMED'
      and asset_symbol in ('TON','USDT','USDC')) <> 3 then
    raise exception 'expected confirmed TON, USDT, and USDC collections';
  end if;
  if exists (select 1 from ledger_balance where chain='TON'
      and (available_balance < 0 or locked_balance < 0 or total_balance < 0)) then
    raise exception 'negative TON ledger balance detected';
  end if;
  if exists (select 1 from ledger_balance where chain='TON' and locked_balance <> 0) then
    raise exception 'non-zero locked TON balance remains';
  end if;
  if exists (select 1 from withdrawal_order where chain='TON' and status <> 'CONFIRMED') then
    raise exception 'unresolved TON withdrawal remains';
  end if;
  if exists (select 1 from collection_record where chain='TON' and status <> 'CONFIRMED') then
    raise exception 'unresolved TON collection remains';
  end if;
end
\$\$;"

printf 'TON PASS local TON/USDT/USDC deposit, replay, withdrawal, collection, BOC retry, and ledger audit\n'
