spring:
  datasource:
    url: ${SW_DB_URL:jdbc:postgresql://172.31.6.134:5432/wallet}
    username: ${SW_DB_USERNAME:wallet}
    password: ${SW_DB_PASSWORD:wallet123}
  data:
    redis:
      host: ${SW_REDIS_HOST:172.31.6.134}
      port: ${SW_REDIS_PORT:6379}
      password: ${SW_REDIS_PASSWORD:}

sw:
  app:
    env:
      name: test2
  wallet:
    admin:
      username: ${SW_WALLET_ADMIN_USERNAME:admin}
      password: ${SW_WALLET_ADMIN_PASSWORD:}
    network: test
    init-default-hot-wallets: ${SW_WALLET_INIT_DEFAULT_HOT_WALLETS:false}
