# ============================================================
# wallet-server configuration
# ============================================================

server:
  port: 8002

logging:
  file:
    path: ./logs

spring:
  application:
    name: wallet-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/wallet
    username: wallet
    password: ${SW_DB_PASSWORD:}
    hikari:
      maximum-pool-size: 20
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
  web:
    error:
      whitelabel:
        enabled: false

# ============================================================
# Application specific config
# ============================================================
sw:
  app:
    env:
      name: dev
  warning:
    contacts: "13261645368"
  wallet:
    admin:
      username: ${SW_WALLET_ADMIN_USERNAME:admin}
      password: ${SW_WALLET_ADMIN_PASSWORD:wallet-admin}
    network: test
    ed25519:
      master-seed: ${SW_ED25519_SEED:}
    legacy:
      eth-withdraw-address: "0xa69c190e7c823fe23dcf6ed7c32877214458d4d3"
      tron-withdraw-address: "TB1x9vmH5SbBd1EUaUePGbZzqmXGosFtxK"
