sw:
  app:
    env:
      name: prod
  wallet:
    admin:
      username: ${SW_WALLET_ADMIN_USERNAME:}
      password: ${SW_WALLET_ADMIN_PASSWORD:}
    network: main
    ed25519:
      master-seed: ${SW_ED25519_SEED:}
    legacy:
      eth-withdraw-address: ${SW_ETH_WITHDRAW_ADDRESS:}
      tron-withdraw-address: ${SW_TRON_WITHDRAW_ADDRESS:}
