-- Cut BTC/LTC/DOGE/BCH runtime signing state over to chain_signing_transaction.
--
-- This migration intentionally does not implement historical fallback. If any
-- legacy BTC-like withdraw_transaction table still contains an active row, the
-- migration stops so an operator can either finish it on the old version or
-- handle it explicitly. Confirmed/deleted historical rows are not copied
-- because runtime confirmation/recovery is keyed by the unified table after
-- this cutover.

create table if not exists chain_signing_transaction (
    id integer generated by default as identity primary key,
    chain varchar(32) not null,
    asset_symbol varchar(32) not null,
    business_type varchar(32) not null,
    business_no varchar(512) not null,
    tx_id varchar(128) not null default '',
    balance numeric(78, 18) not null default 0,
    signature text,
    currency integer not null,
    status smallint not null,
    error_message text,
    create_date timestamptz not null default now(),
    update_date timestamptz not null default now(),
    unique (chain, business_type, business_no)
);

create index if not exists idx_chain_signing_transaction_tx_id
    on chain_signing_transaction(chain, tx_id);
create index if not exists idx_chain_signing_transaction_status
    on chain_signing_transaction(chain, status, update_date);

do $$
declare
    active_count bigint;
    table_count bigint;
begin
    active_count := 0;

    if to_regclass('btc_withdraw_transaction') is not null then
        select count(*) into table_count from btc_withdraw_transaction where status in (0, 1, 2);
        active_count := active_count + table_count;
    end if;
    if to_regclass('ltc_withdraw_transaction') is not null then
        select count(*) into table_count from ltc_withdraw_transaction where status in (0, 1, 2);
        active_count := active_count + table_count;
    end if;
    if to_regclass('doge_withdraw_transaction') is not null then
        select count(*) into table_count from doge_withdraw_transaction where status in (0, 1, 2);
        active_count := active_count + table_count;
    end if;
    if to_regclass('bch_withdraw_transaction') is not null then
        select count(*) into table_count from bch_withdraw_transaction where status in (0, 1, 2);
        active_count := active_count + table_count;
    end if;

    if active_count > 0 then
        raise exception
            'refusing BTC-like signing cutover: % active legacy withdraw_transaction rows still exist',
            active_count;
    end if;

    if to_regclass('btc_withdraw_transaction') is not null then
        insert into chain_signing_transaction(
            chain, asset_symbol, business_type, business_no, tx_id, balance,
            signature, currency, status, create_date, update_date
        )
        select 'BTC', 'BTC', 'LEGACY', 'btc_withdraw_transaction:' || id,
               tx_id, balance, signature, currency, status, create_date, update_date
        from btc_withdraw_transaction
        where status not in (0, 1, 2)
        on conflict (chain, business_type, business_no) do nothing;
    end if;

    if to_regclass('ltc_withdraw_transaction') is not null then
        insert into chain_signing_transaction(
            chain, asset_symbol, business_type, business_no, tx_id, balance,
            signature, currency, status, create_date, update_date
        )
        select 'LTC', 'LTC', 'LEGACY', 'ltc_withdraw_transaction:' || id,
               tx_id, balance, signature, currency, status, create_date, update_date
        from ltc_withdraw_transaction
        where status not in (0, 1, 2)
        on conflict (chain, business_type, business_no) do nothing;
    end if;

    if to_regclass('doge_withdraw_transaction') is not null then
        insert into chain_signing_transaction(
            chain, asset_symbol, business_type, business_no, tx_id, balance,
            signature, currency, status, create_date, update_date
        )
        select 'DOGE', 'DOGE', 'LEGACY', 'doge_withdraw_transaction:' || id,
               tx_id, balance, signature, currency, status, create_date, update_date
        from doge_withdraw_transaction
        where status not in (0, 1, 2)
        on conflict (chain, business_type, business_no) do nothing;
    end if;

    if to_regclass('bch_withdraw_transaction') is not null then
        insert into chain_signing_transaction(
            chain, asset_symbol, business_type, business_no, tx_id, balance,
            signature, currency, status, create_date, update_date
        )
        select 'BCH', 'BCH', 'LEGACY', 'bch_withdraw_transaction:' || id,
               tx_id, balance, signature, currency, status, create_date, update_date
        from bch_withdraw_transaction
        where status not in (0, 1, 2)
        on conflict (chain, business_type, business_no) do nothing;
    end if;
end $$;
