server.port=8081
spring.application.name=wallet-sig2
atomex.wallet.network=test
# Nacos service discovery
spring.cloud.nacos.discovery.server-addr=nacos.atomex.pro:8848
spring.cloud.nacos.discovery.namespace=c9d64380-5fa8-428d-9b81-73b3f69272bc
