server:
  port: 8004

logging:
  config: classpath:logback-spring.xml
  level:
    default: INFO
  file:
    path: logs/

spring:
  application:
    name: wallet-sig1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SW_DB_URL:jdbc:postgresql://127.0.0.1:5432/wallet}
    username: ${SW_DB_USERNAME:wallet}
    password: ${SW_DB_PASSWORD:}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:

sw:
  wallet:
    network: test
